Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2019-12, with the labels that each got.

#1070 CreateItem will only retry for auto-extracted partition key in-case of container re-creation
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/RequestHandlerHelper.cs
  changelog.md
Labels: bug

#1091 Fix SplitException
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosQueryClientCoreTest.cs
  changelog.md
Labels: QUERY, bug

#1089 Bulk API - Operations with no PK
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
  changelog.md
Labels: Bulk, bug

#1087 Fixed missing store result info from diagnostics
  Microsoft.Azure.Cosmos/src/Diagnostics/PointOperationStatistics.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosClientSideRequestStatistics.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PointOperationStatisticsTest.cs
  changelog.md
Labels: Diagnostics, bug

#940 Updated forked files to match the latest internal EN20190919 branch
  Microsoft.Azure.Cosmos/src/AuthorizationHelper.cs
  Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/DocumentClientWithUriParameters.cs
  Microsoft.Azure.Cosmos/src/FeedOptions.cs
  Microsoft.Azure.Cosmos/src/IRequestSigner.cs
  Microsoft.Azure.Cosmos/src/NullRequestSigner.cs
  Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentFeedResponse.cs
  Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
  Microsoft.Azure.Cosmos/src/ResourceFeedReaderClientExtensions.cs
  Microsoft.Azure.Cosmos/src/ResourceThrottleRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs
  Microsoft.Azure.Cosmos/src/Routing/AsyncCache.cs
  Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
  Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs
  Microsoft.Azure.Cosmos/src/Routing/CollectionRoutingMap.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AsyncCacheTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/ParallelAsync.cs
Labels: Engineering

#1078 SynchronizationContext and blocking calls
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/PermissionProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserCore.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserInlineCore.cs
  Microsoft.Azure.Cosmos/src/TaskHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosQueryClientCoreTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosSpatialTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/NonPartitionedContainerHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorBuilderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TaskHelperTests.cs
  changelog.md
Labels: bug

#1110 Missing Etag on DatabaseProperties
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/AccountProperties.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/DatabaseProperties.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/StoredProcedureProperties.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/ThroughputProperties.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/TriggerProperties.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/UserDefinedFunctionProperties.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: VNext
