Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2019-09, with the labels that each got.

#756 Change Feed Processor with StartTime calls handler with 0 results
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  changelog.md
Labels: bug

#743 Add support for proxy
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractEnforcement.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
  changelog.md
Labels: feature

#753 Error reason not propagating on some status codes
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosExceptionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  changelog.md
Labels: bug

#763 Refactor query client for Query Core
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/ItemProducerTree.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/ContainerQueryProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
Labels: Engineering, QUERY

#769 Session being updated incorrectly on Gateway mode
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  changelog.md
Labels: bug

#741 Preview of Bulk Stream
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncBatcher.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchOperationResult.cs
  Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperationContext.cs
  Microsoft.Azure.Cosmos/src/BulkPartitionKeyRangeGoneRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Labels: Batch, feature

#779 Fixing CosmosSerializer comments
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializer.cs
Labels: documentation

#776 Converted all aggregate linq queries to return Response<T>
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosDiagnosticsAggregate.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: LINQ, QUERY, feature

#783 Fix wrong Gateway connection protocol
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Labels: bug

#767 Ability to limit to configured application region only
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: breaking, feature

#772 Throughput fix for throwing on not found and using custom serializer
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/CosmosSerializerHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  changelog.md
Labels: bug

#785 Incorrect key to throw CosmosExceptions with HttpStatusCode.Unauthorized status code
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs
  changelog.md
Labels: bug

#799 Fixing diagnostics tests
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/ItemBatchOperationStatisticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyBatchResponseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
Labels: Engineering, bug

#782 Adding Change Feed Processor code migration sample
  Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs
Labels: ChangeFeed, Samples

#806 Query core refactoring to remove dependency on QueryRequestOptions
  Microsoft.Azure.Cosmos/src/Query/CosmosCrossPartitionQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosOrderByItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosParallelItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContextCore.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/PipelinedDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/Query/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
Labels: QUERY

#821 Adding release and retirement date to changelog
  changelog.md
Labels: documentation

#822 Enabling client side GROUP BY
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContextCore.cs
  Microsoft.Azure.Cosmos/src/Query/PipelinedDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
Labels: QUERY

#830 Update change log to include preview releases
  changelog.md
Labels: documentation

#814 Limit to endpoint feature
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: feature

#811 Query core removing using Documents to fix ambiguous references
  Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElementJsonConverter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonObjectState.cs
  Microsoft.Azure.Cosmos/src/Json/JsonParseException.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Collections/AsyncCollection.cs
  Microsoft.Azure.Cosmos/src/Query/Core/CompositeContinuationToken.cs
  Microsoft.Azure.Cosmos/src/Query/Core/DistinctMap.UnorderedDistinctMap.cs
  Microsoft.Azure.Cosmos/src/Query/Core/DistinctMap.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/AggregateDocumentQueryExecutionComponent.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/DistinctDocumentQueryExecutionComponent.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/SkipDocumentQueryExecutionComponent.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/TakeDocumentQueryExecutionComponent.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosCrossPartitionQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosOrderByItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosParallelItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/PipelinedDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ItemComparer.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ItemProducerTree/ItemProducer.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ItemProducerTree/ItemProducerTree.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Number64.cs
  Microsoft.Azure.Cosmos/src/Query/Core/OrderByQuery/OrderByConsumeComparer.cs
  Microsoft.Azure.Cosmos/src/Query/Core/OrderByQuery/OrderByContinuationToken.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ParallelQuery/ParallelItemProducerTreeComparer.cs
  Microsoft.Azure.Cosmos/src/Query/Core/PartitionedQueryExecutionInfo.cs
  Microsoft.Azure.Cosmos/src/Query/Core/PartitionedQueryExecutionInfoInternal.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/QueryResponseCore.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlanHandler.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/src/Query/Core/UInt192.cs
  Microsoft.Azure.Cosmos/src/Query/v2Query/DefaultDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryContextCore.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
  Microsoft.Azure.Cosmos/src/Routing/RangeJsonConverter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
Labels: QUERY

#835 Fixed a bug that caused sortedRanges exception
  Microsoft.Azure.Cosmos/src/Routing/IRoutingMapProviderExtensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/IRoutingMapProviderExtensionsTest.cs
  changelog.md
Labels: QUERY, bug

#841 Adding IndexManagement samples
  Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
  Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/IndexManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/Program.cs
Labels: Samples

#848 Spatial Index contract change
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Labels: Engineering

#844 Adding PartitionKeyDefinitionVersion to container builder.
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: feature

#846 Statistics not getting populated correctly on CosmosException
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosClientSideRequestStatistics.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  changelog.md
Labels: bug

#859 Bulk retry on namestale
  Microsoft.Azure.Cosmos/src/BulkPartitionKeyRangeGoneRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
Labels: bug
