Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2019-08, with the labels that each got.

#612 Fixed a bug with read feed with partition key.
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/src/Handler/RouterHandler.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResponseMessageTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
  changelog.md
Labels: QUERY, bug

#614 Fixed SpatialPath serialization and compatibility with older index versions
  Microsoft.Azure.Cosmos/src/CosmosIndexJsonConverter.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/Index.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/SpatialPath.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/NonPartitionedContainerHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
  changelog.md
Labels: bug

#627 CosmosContainerBuilder with public constructor
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Labels: bug

#626 FeedResponse<T> status code now return OK for success instead of the invalid status code 0 or Accepted
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockItemProducerFactory.cs
  changelog.md
Labels: QUERY, bug

#630 Enrich user-agent with runtime context
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/EnvironmentInformationTests.cs
  changelog.md
Labels: feature

#648 StandByFeedIterator to continue on NotModified
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIteratorCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
Labels: breaking

#650 Enabling serialization customization through CosmosSerializerOptions
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElementSerializer.cs
  Microsoft.Azure.Cosmos/src/FeedOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonSerializerWrapper.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosPropertyNamingPolicy.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializationFormatOptions.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializationOptions.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractEnforcement.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
  changelog.md
Labels: breaking, bug

#673 ChangeFeed Samples
  Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
Labels: ChangeFeed

#680 Adding sample to run powershell rest api
  Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellRestApi.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/CreateContainer.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/CreateDB.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/CreateItem.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/DeleteContainer.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/DeleteDB.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/DeleteItem.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/ReadContainer.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/ReadDB.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/ReadItem.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/ReplaceContainer.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/ReplaceItem.ps1
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/Program.cs
Labels: Samples

#702 Scaled out StandByFeedIterator
  Microsoft.Azure.Cosmos/src/Query/StandByFeedContinuationToken.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StandByFeedContinuationTokenTests.cs
Labels: feature

#713 Fixed flaky tests: ValidateAsync, TestOpenAsyncFailFast, GetCosmosSerializerWithWrapperOrDefaultWithOptionsTest
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Labels: Engineering, bug

#622 ResourceToken support
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/Permission.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionMode.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosFeedResponseUtil.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/PermissionProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/UserProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/User/User.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserCore.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserResponse.cs
  Microsoft.Azure.Cosmos/src/ResourceFeedReaderClientExtensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosUserTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DocumentClientLinkSwitchExtension.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosPermissionUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/ContainerDocsSampleCode.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/CustomDocsSampleCode.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/DatabaseDocsSampleCode.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/ItemDocsSampleCode.cs
  changelog.md
Labels: feature

#585 Bulk stream support
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncBatcher.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncStreamer.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchExecUtils.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchResponse.cs
  Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
  Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperationContext.cs
  Microsoft.Azure.Cosmos/src/Batch/PartitionKeyRangeBatchExecutionResult.cs
  Microsoft.Azure.Cosmos/src/Batch/PartitionKeyRangeBatchResponse.cs
  Microsoft.Azure.Cosmos/src/Batch/PartitionKeyRangeServerBatchRequest.cs
  Microsoft.Azure.Cosmos/src/Batch/ServerBatchRequest.cs
  Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
  Microsoft.Azure.Cosmos/src/ClientResources.resx
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/src/Util/InterlockIncrementCheck.cs
  Microsoft.Azure.Cosmos/src/Util/UsableSemaphoreWrapper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyBatchResponseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeServerBatchRequestTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/InterlockIncrementCheckTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/UsableSemaphoreWrapperTests.cs
Labels: feature

#720 Update CosmosClientOptions serializer documentation
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Labels: documentation

#726 Query iterator HasMoreResults now returns false if an exception is hit
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  changelog.md
Labels: QUERY, bug

#732 Adding tests to cover Batch request overflow
  Microsoft.Azure.Cosmos/src/Batch/ServerBatchRequest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeServerBatchRequestTests.cs
Labels: Engineering, bug

#705 Fix for longer UserAgent suffix
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs
  Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  changelog.md
Labels: bug

#716 Adding camel case serialization on LINQ query generation
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
  Microsoft.Azure.Cosmos/src/Linq/DocumentQueryEvaluator.cs
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Linq/SQLTranslator.cs
  Microsoft.Azure.Cosmos/src/Linq/TranslationContext.cs
  Microsoft.Azure.Cosmos/src/Linq/TypeSystem.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializationOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/ToDoActivity.cs
  changelog.md
Labels: bug

#730 Cross Partition Non Value Aggregates
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/Query/Aggregation/SingleGroupAggregator.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/DocumentQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/ExecutionComponent/AggregateDocumentQueryExecutionComponent.cs
  Microsoft.Azure.Cosmos/src/Query/ExecutionComponent/GroupByDocumentQueryExecutionComponent.cs
  Microsoft.Azure.Cosmos/src/Query/PipelinedDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/QueryFeature.cs
  Microsoft.Azure.Cosmos/src/Query/QueryInfo.cs
  Microsoft.Azure.Cosmos/src/Query/QueryPlanHandler.cs
  Microsoft.Azure.Cosmos/src/Query/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAny.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAggregateFunctionsBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPartitionProviderTest.Aggregates.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPartitionProviderTest.Negative.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPartitionProviderTest.NonValueAggregate.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ComparableTaskSchedulerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Labels: QUERY, feature

#729 Adding aggregate(CountAsync/SumAsync etc.) extensions for LINQ query
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
  Microsoft.Azure.Cosmos/src/Linq/DocumentQueryable.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Linq/CosmosLinqAggregateFunctionTest.cs
  changelog.md
Labels: LINQ
