Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2019-05, with the labels that each got.

#227 Exception-less Streaming API for non-existing NP container scenarios
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/CosmosRequestMessage.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
  Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs
  Microsoft.Azure.Cosmos/src/Util/ExecUtils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Labels: bug

#141 Replacing Proxy with Query Plan Retriever
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosGatewayQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosProxyItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
  Microsoft.Azure.Cosmos/src/Query/QueryFeature.cs
  Microsoft.Azure.Cosmos/src/Query/QueryPlanHandler.cs
  Microsoft.Azure.Cosmos/src/Query/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: improvement

#251 Making CosmosClientContext internal for Friends
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
Labels: feature

#252 Porting to release branch making CosmosClientContext internal to unblock Friends
  Microsoft.Azure.Cosmos.Samples/CodeSamples/NuGet.config
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
Labels: feature

#258 Roundtrip Optimization For Binary Encoding
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
Labels: Required for GA

#278 Not found fix for release branch
  Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosQueryResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
Labels: Required for GA, bug

#290 TestReducePageSizeScenario failing on CI
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Labels: Engineering, bug

#285 Rename all iterators to be plural
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabases.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/StoredProcedure/CosmosStoredProcedures.cs
  Microsoft.Azure.Cosmos/src/Resource/StoredProcedure/CosmosStoredProceduresCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Trigger/CosmosTriggers.cs
  Microsoft.Azure.Cosmos/src/Resource/UserDefinedFunction/CosmosUserDefinedFunctions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.OnePartition.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
Labels: Required for GA, breaking

#294 CosmosContainerSettings.LastModified is now ignored if null
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
Labels: Internal team blocked, bug

#286 Rename CosmosClientConfiguration -> CosmosClientOptions
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.OnePartition.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
Labels: Required for GA, breaking

#250 Renamed all cancellationToken parameters
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Query/QueryPlanHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
Labels: breaking, improvement

#157 CosmosContainerSettings Fluent API support
  Microsoft.Azure.Cosmos/src/Fluent/Settings/CompositeIndexFluentDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/CosmosContainerFluentDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/CosmosContainerFluentDefinitionForCreate.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/IndexingPolicyFluentDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/PathsFluentDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/SpatialIndexFluentDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/UniqueKeyFluentDefinition.cs
  Microsoft.Azure.Cosmos/src/IndexingPolicyBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/UniqueKey.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/CosmosContainerSettingsFluentTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexingPolicyEqualityComparer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexingPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/CompositeIndexFluentDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/CosmosContainerFluentDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/IndexingPolicyFluentDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/PathsFluentDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/SpatialIndexFluentDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/UniqueKeyFluentDefinitionTests.cs
Labels: Required for GA

#281 Fix item query not found exceptions
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Headers/CosmosQueryResponseMessageHeaders.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Labels: Internal team blocked, Required for GA, bug

#291 Add a default serializer
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingWorkEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosJsonSerializerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosConflictSettings.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosResource.cs
  Microsoft.Azure.Cosmos/src/Scripts/CosmosScriptsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosSpatialTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/RemainingWorkEstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: Required for GA, feature

#311 CosmosConsistencySettings to CosmosAccountConsistency
  Microsoft.Azure.Cosmos/src/Resource/Settings/ConsistencyLevel.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosAccountConsistency.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosAccountSettings.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: breaking

#312 Inlineing CosmosContainerItems into CosmosContainer
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseStoreCosmos.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/CosmosJsonSerializer.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Scripts/CosmosScriptsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosSpatialTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.OnePartition.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/CosmosContainerSettingsFluentTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/DocumentBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ExceptionlessTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Labels: breaking

#316 CosmosClient creation through CosmosClientOptions
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Labels: breaking

#319 Metadata {Create/Replace}AsStreamAsync updated to take settings as arguments
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabases.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
Labels: breaking

#249 Enabling Cross Partition OFFSET LIMIT
  Microsoft.Azure.Cosmos/src/FeedOptions.cs
  Microsoft.Azure.Cosmos/src/Query/PipelinedDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
Labels: Required for GA

#329 Release branch name cache fix
  Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Routing/NonRetriableInvalidPartitionExceptionRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
Labels: bug

#326 Add support to mock the cosmos client.
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosVirtualUnitTest.cs
Labels: Required for GA, feature

#328 Session Token as promoted property in Headers
  Microsoft.Azure.Cosmos/src/Headers/CosmosResponseMessageHeaders.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/ItemResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosResponseMessageHeadersTests.cs
Labels: Required for GA
