Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2019-06, with the labels that each got.

#347 Documentation: System properties (Json property documentation)
  Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs
  Microsoft.Azure.Cosmos.Samples/CodeSamples/Shared/Metadata.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
Labels: Required for GA

#209 Linq in V3 SDK
  Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
  Microsoft.Azure.Cosmos/src/Linq/DocumentQueryEvaluator.cs
  Microsoft.Azure.Cosmos/src/Linq/DocumentQueryable.cs
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Linq/QueryUnderConstruction.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlGroupByClause.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlNumberLiteral.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlObjectKind.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlQuery.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectHasher.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectObfuscator.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectTextSerializer.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectVisitor.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/BaselineTestInput.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/BaselineTestOutput.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/BaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateAvg.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateCount.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateMax.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateMin.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateSum.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAny.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAttributeContractBaselineTests.TestNewAttributeContract.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestDistinctTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestOrderByTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestQueryFlattening.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestSelectMany.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestSimpleSubquery.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestSkipTake.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestSubquery.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.ValidateDynamicLinq.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.ValidateLinqQueries.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestArrayFunctions.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestClausesOrderVariations.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestConditional.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestMathFunctions.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestNullableFields.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestSelectManyWithFilters.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestSelectTop.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestStringCompareTo.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestStringEnumJsonConverter.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestStringFunctions.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestUDFs.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAggregateFunctionsBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAttributeContractBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqConstantFoldingBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqSQLTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTestData.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Labels: Required for GA

#348 PartitionKey class instead of object
  Microsoft.Azure.Cosmos/src/ChangeFeedOptions.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdater.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterInMemory.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/PartitionedByIdCollectionRequestOptionsFactory.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/RequestOptionsFactory.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/SinglePartitionRequestOptionsFactory.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/FeedOptions.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/PartitionKey.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/DocumentQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosConflicts.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs
  Microsoft.Azure.Cosmos/src/Scripts/CosmosScripts.cs
  Microsoft.Azure.Cosmos/src/Scripts/CosmosScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Util/ExecUtils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosSpatialTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/CosmosContainerSettingsFluentTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/PartitionKeyTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/DocumentBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterInMemoryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ExceptionlessTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs
Labels: Required for GA, breaking

#368 Adding test to cover default serialization behavior
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
Labels: Engineering, Required for GA

#370 Re-enable TestReducePageSizeScenario
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Labels: Engineering

#372 Revert [AsStream] back to [Stream]
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabase.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Scripts/CosmosScriptsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/DocumentBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Labels: ADP-Feedback, breaking

#383 Azure Functions sample fix
  Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/Startup.cs
Labels: bug

#369 ExecuteStoredProcedure with Streams support
  Microsoft.Azure.Cosmos/src/Scripts/CosmosScripts.cs
  Microsoft.Azure.Cosmos/src/Scripts/CosmosScriptsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
Labels: Required for GA, feature

#381 GetConflicts instead of property
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: Required for GA, breaking

#389 Rename requestUnits to requestUnitsPerSecond
  Microsoft.Azure.Cosmos/src/Fluent/Settings/CosmosContainerFluentDefinitionForCreate.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabase.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOfferResult.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DirectRESTTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Labels: Required for GA, breaking

#390 Rename workflowName and WithCosmosLeaseContainer
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorBuilderTests.cs
Labels: Required for GA, breaking

#382 Removed virtual from data contracts
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosConflictSettings.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosDatabaseSettings.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosStoredProcedureSettings.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosVirtualUnitTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: Required for GA, breaking

#189 Query stream contract match BE stream contract
  Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElementSerializer.cs
  Microsoft.Azure.Cosmos/src/Headers/CosmosQueryResponseMessageHeaders.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosCrossPartitionQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/CrossPartitionQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/ExecutionComponent/AggregateDocumentQueryExecutionComponent.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemProducerUnitTests.cs
Labels: Required for GA, breaking, improvement

#377 Read feed correctly handle 410 gone.
  Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/CosmosRequestMessage.cs
  Microsoft.Azure.Cosmos/src/Handler/NamedCacheRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/RetryHandler.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosGatewayQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/DefaultDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Routing/InvalidPartitionExceptionRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
Labels: Internal team blocked, bug

#401 Add support for account key as secure string
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
Labels: feature

#398 Refactor file structure to align with class hierarchy
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ItemResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabase.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/CosmosScripts.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/CosmosScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsExtensions.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/StoredProcedureExecuteResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/StoredProcedureResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/TriggerResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/UserDefinedFunctionResponse.cs
Labels: Engineering

#404 Fix query continuation token throw
  Microsoft.Azure.Cosmos/src/FeedResponseBinder.cs
  Microsoft.Azure.Cosmos/src/Linq/DocumentQuery.cs
  Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosQueryResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosResultSetIteratorCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Labels: Internal team blocked, bug

#410 Release patch feed operations
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/Routing/InvalidPartitionExceptionRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/NonRetriableInvalidPartitionExceptionRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: Internal team blocked, bug

#426 Renaming requestUnitsPerSecond to throughput
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerFluentDefinitionForCreate.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabase.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOfferResult.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DirectRESTTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Labels: Required for GA, breaking

#431 Parameter order in item operations
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/CosmosContainerSettingsFluentTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/DocumentBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Labels: Required for GA, breaking

#433 Change Feed Processor public API name changes
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedEstimatorDispatcher.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverBase.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverFactoryCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorCoreTests.cs
Labels: Required for GA, breaking

#425 Query API's renames
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingWorkEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExtensions.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedPartitionKeyResultSetIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetStreamIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/UserDefinedFunctionProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/RemainingWorkEstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: DO NOT MERGE, discussion-wanted

#443 CosmosDatabase -> Rename to Database
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/DocumentClientWithUriParameters.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/CreateContainerDefinition.cs
  Microsoft.Azure.Cosmos/src/IDocumentClient.cs
  Microsoft.Azure.Cosmos/src/Linq/DocumentClientQueryable.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosResource.cs
  Microsoft.Azure.Cosmos/src/ResourceFeedReaderClientExtensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosSpatialTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DirectRESTTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DocumentClientLinkSwitchExtension.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexingPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAggregateFunctionsBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAttributeContractBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqSQLTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs
Labels: Required for GA, breaking

#449 Builders Get contract
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ConflictResolutionDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/UniqueKeyDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/CompositeIndexDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ConflictResolutionDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/IndexingPolicyDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/PathsDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/SpatialIndexDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/UniqueKeyDefinitionTests.cs
Labels: Required for GA, breaking

#446 Unifying Header classes
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Headers/CosmosQueryResponseMessageHeaders.cs
  Microsoft.Azure.Cosmos/src/Headers/Headers.cs
  Microsoft.Azure.Cosmos/src/Headers/HeadersBase.cs
  Microsoft.Azure.Cosmos/src/Headers/RequestHeaders.cs
  Microsoft.Azure.Cosmos/src/Headers/ResponseHeaders.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ItemResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Response.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/StoredProcedureExecuteResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/StoredProcedureResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/TriggerResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/UserDefinedFunctionResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HeadersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RequestHeadersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResponseMessageHeadersTests.cs
Labels: Required for GA

#402 Throughput resource model public api change .
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ThroughputProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Throughput/ThroughputResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Labels: discussion-wanted, feature

#455 Move query parameters to request options
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryRequestOptionsUniTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: Required for GA, breaking

#467 CosmosException response headers are public and adding retry after
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Labels: feature

#465 Update comments and fix spelling mistakes
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Configuration/CheckpointFrequency.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingLeaseTokenWork.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingWorkEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosSerializer.cs
  Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/NamedCacheRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeGoneRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/StoredProcedureResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/TriggerResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/AccountRegion.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CompositePath.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictResolutionPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosAccountServiceConfiguration.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/DatabaseProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/IncludedPath.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/Index.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/PartititonKeyDefinitionVersion.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ThroughputProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/UserDefinedFunctionProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UniqueIndexTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Labels: documentation

#473 Adding specific constructors to PartitionKey
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/SinglePartitionRequestOptionsFactory.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/PartitionKey.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterInMemoryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs
Labels: breaking, feature

#480 Make CosmosClient creation non-blocking
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Labels: bug

#481 Merge query and read feed
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedStatelessIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: Required for GA, breaking, feature

#373 Query correctly handles collection recreates
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/NamedCacheRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/src/Handler/RetryHandler.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/DefaultDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
  Microsoft.Azure.Cosmos/src/Query/PartitionKeyRangeGoneRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/ChangeFeedRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/Routing/InvalidPartitionExceptionRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ExceptionlessTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResponseMessageTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StandByFeedContinuationTokenTests.cs
Labels: Required for GA, bug

#488 Changing PartitionKey to struct from class
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManagerInMemory.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/PartitionKey.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Util/ExecUtils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Labels: Required for GA

#492 Change Feed Processor supporting fixed lease containers
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Labels: bug
