Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2019-07, with the labels that each got.

#501 Release branch query fixes for empty page
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/Query/CosmosCrossPartitionQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosOrderByItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosParallelItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
Labels: Internal team blocked, bug

#506 Enabling faulty tests
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ConflictResolutionDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictResolutionPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
Labels: Engineering

#503 StandByFeedIterator with no StartTime
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
Labels: bug

#512 Remove GC.SuppressFinalize from response message
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
Labels: Required for GA, bug

#507 Making LINQ extension classes public
  Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
  Microsoft.Azure.Cosmos/src/ClientResources.resx
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/BuiltinFunctionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/SpatialBuiltinFunctions.cs
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/SqlBuiltinFunctionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExtensions.cs
  Microsoft.Azure.Cosmos/src/Spatial/Geometry.cs
  Microsoft.Azure.Cosmos/src/Spatial/GeometryOperationExtensions.cs
  Microsoft.Azure.Cosmos/src/Spatial/GeometryValidationResult.cs
  Microsoft.Azure.Cosmos/src/TypeCheckFunctionsExtensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractTests.cs
Labels: Required for GA

#500 Query fixes for trace print race condition and draining with empty pages
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeHandler.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosCrossPartitionQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosOrderByItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosParallelItemQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/ItemProducerTree.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/DocumentProducer.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ParallelItemProducerTreeComparer.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetStreamIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedStatelessIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockItemProducerFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ToDoItem.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: Internal team blocked, Required for GA, bug

#520 Fixed query handling 429s by removing unnecessary null check.
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: Required for GA, bug

#515 Stored procedure execute is updated to use params
  Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/CustomDocsSampleCode.cs
Labels: Required for GA, breaking

#511 Split fixes and split mock tests
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/ItemProducerTree.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockItemProducerFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
Labels: Required for GA, bug

#531 Fix query split bug loses continuation token
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/DocumentProducer.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockItemProducerFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockResponseForSinglePartition.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ToDoItem.cs
Labels: Required for GA, bug

#533 Porting Fix query split bug loses continuation token (#531) to releases\3.0.0
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/DocumentProducer.cs
  Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockItemProducerFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockResponseForSinglePartition.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ToDoItem.cs
Labels: bug

#534 Updated to 3.0.0 GA nuget
  Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/AzureFunctions.csproj
  Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/ContainerManagement.csproj
  Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/DatabaseManagement.csproj
  Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers/HandlerSample.csproj
  Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/ItemManagement.csproj
  Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs
  Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj
  Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs
  Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Queries.csproj
  Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs
  Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/ServerSideScripts.csproj
Labels: improvement

#535 3.0.0.16 preview6 version bump
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Labels: Internal team blocked

#548 Fix mis-typed message in CosmosException.ToString()
  Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
Labels: bug

#427 Batch CRUD API
  Microsoft.Azure.Cosmos/src/Batch/Batch.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchExecUtils.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchOperationResult.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchResponse.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchSchemaProvider.cs
  Microsoft.Azure.Cosmos/src/Batch/HybridRowBatchSchemas.json
  Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
  Microsoft.Azure.Cosmos/src/Batch/ServerBatchRequest.cs
  Microsoft.Azure.Cosmos/src/Batch/SinglePartitionKeyServerBatchRequest.cs
  Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
  Microsoft.Azure.Cosmos/src/ClientResources.resx
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingDirective.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchExecUtilsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchRequestPayloadReader.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchResponsePayloadWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BatchUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Labels: feature

#544 Adding continuation token support for LINQ
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  changelog.md
Labels: Release-Notes

#552 Adding query tests for order by and continuation token
  Microsoft.Azure.Cosmos/src/Query/OrderByItem.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockPartitionResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockResponseForSinglePartition.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
Labels: Engineering, QUERY

#521 Updating change log
  README.md
  changelog.md
Labels: documentation

#558 LocationCache ConcurrentDict lock contention fix
  Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
  changelog.md
Labels: Release-Notes

#541 Add consistency level to client and query options
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/StoredProcedureRequestOptions.cs
  Microsoft.Azure.Cosmos/src/ValidationHelpers.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
  changelog.md
Labels: feature

#561 GetItemLinqQueryable now works with null query
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  changelog.md
Labels: bug

#557 Making item request option triggers public
  Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
  changelog.md
Labels: Release-Notes, feature

#567 Query correctly handles different language cultures
  Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonTextUtil.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonTextWriter.cs
  Microsoft.Azure.Cosmos/src/Json/NewtonsoftInterop/JsonNewtonsoftReader.cs
  Microsoft.Azure.Cosmos/src/Json/NewtonsoftInterop/JsonNewtonsoftWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTokenInfo.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
  changelog.md
Labels: QUERY, bug

#571 Expose a default JSON.net serializer with optional settings
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingWorkEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosJsonDotNetSerializer.cs
  Microsoft.Azure.Cosmos/src/CosmosJsonSerializerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosResource.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosSpatialTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/RemainingWorkEstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
  changelog.md
Labels: feature

#530 Moving offer operations to new V3 pipeline
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Labels: improvement

#574 Fixed empty error message if query parsing fails from unexpected exception.
  Microsoft.Azure.Cosmos/src/Query/QueryPartitionProvider.cs
  changelog.md
Labels: Engineering, QUERY, bug

#576 Query correctly serializes the input into a stream
  Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosSqlQuerySpecJsonConverter.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/SqlQuerySpec.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/CosmosSerializerHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  changelog.md
Labels: QUERY, bug

#587 Bumping direct version to 3.0.3
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/Microsoft.Azure.Cosmos.NetFramework.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Labels: Engineering

#592 Adding CreateIfNotExistsAsync to container builder
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: feature

#593 Updated debug check for batch operation
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
Labels: Internal team blocked

#594 Fixing typo error.
  Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs
Labels: documentation

#598 Missing count increment in Sample preventing Assert from ever failing
  Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs
Labels: bug

#597 Adding continuation token property to response message
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: feature

#581 Adding ToQueryDefinition method on an IQueryable
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryDefinition.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryDefinitionUnitTests.cs
  changelog.md
Labels: feature

#604 Adding ToStreamIterator for LINQ
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/ToDoActivity.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: feature

#609 Updating samples to 3.1.0 nuget.
  Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/ContainerManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/DatabaseManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/JS/OrderBy.js
  Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/ServerSideScripts.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Shared/Shared.csproj
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Engineering, feature
