Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-08, with the labels that each got.

#1721 LINQ : Adds support for case-insensitive searches
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestSpecialMethods.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestStringFunctions.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
Labels: LINQ, QUERY, feature

#1754 [Internal] Tests: Fixes contract update tool
  UpdateContracts.ps1
Labels: Engineering

#1768 SessionToken: Adds optimization to remove session token for stored procedure, triggers, and UDFs
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Labels: bug

#1711 [Internal] ChangeFeedProcessor: Adds more detailed logging of 404 conditions
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/DocDBErrors/DocDbError.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/DocDBErrors/ExceptionClassifier.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Exceptions/FeedException.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Exceptions/FeedNotFoundException.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Exceptions/FeedReadSessionNotAvailableException.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Exceptions/FeedSplitException.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionSupervisorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverCloseReason.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/Exceptions/FeedNotFoundExceptionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/Exceptions/FeedReadSessionNotAvailableExceptionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSupervisorTests.cs
Labels: ChangeFeed

#1775 [Internal] Samples: Adds HttpClientFactory usage samples
  Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
  Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/HttpClientFactory.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/Program.cs
Labels: Samples

#1777 [Internal] Release yaml: Fixes release pipeline
  azure-pipelines-official.yml
Labels: Engineering

#1789 Troubleshooting Docs: Refactors cleanup the troubleshooting guides that are now in Azure Docs
  Exceptions.md
  TroubleshootingGuides/CosmosDotNetRequestTimeout.md
  TroubleshootingGuides/CosmosMacSignature.md
  TroubleshootingGuides/CosmosNotFound.md
  TroubleshootingGuides/CosmosNotModified.md
  TroubleshootingGuides/CosmosRequestHeaderTooLarge.md
  TroubleshootingGuides/CosmosRequestRateTooLarge.md
  TroubleshootingGuides/CosmosServiceRequestTimeout.md
  TroubleshootingGuides/CosmosServiceUnavailable.md
  TroubleshootingGuides/Exceptions.md
Labels: documentation

#1660 Client side encryption: Add AzureKeyVault implementation of KeyWrapProvider
  Microsoft.Azure.Cosmos.Encryption/src/AssemblyKeys.cs
  Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapProvider.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/AzureKeyVaultCosmosEncryptor.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/AzureKeyVaultKeyWrapMetadata.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/AzureKeyVaultKeyWrapProvider.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/CryptographyClientFactory.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/KeyClientFactory.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/KeyVaultAccessClient.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/KeyVaultAccessException.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/KeyVaultConstants.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/KeyVaultKeyUriProperties.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/KeyVaultTokenCredentialFactory.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/UserProvidedTokenCredentialFactory.cs
  Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
  Microsoft.Azure.Cosmos.Encryption/src/Mirrored/UnixDateTimeConverter.cs
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/EncryptionTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/KeyVaultAccessClientTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
  Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json
  Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
  Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Encryption.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/Encryption/appSettings.json
  Microsoft.Azure.Cosmos.Samples/Usage/appSettings.json
Labels: feature

#1781 Performance: Adds headers optimization
  Microsoft.Azure.Cosmos/src/Headers/CosmosCustomHeader.cs
  Microsoft.Azure.Cosmos/src/Headers/CosmosKnownHeaderAttribute.cs
  Microsoft.Azure.Cosmos/src/Headers/CosmosMessageHeadersInternal.cs
  Microsoft.Azure.Cosmos/src/Headers/Headers.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosCustomHeaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HeadersTests.cs
Labels: Performance
