Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-03, with the labels that each got.

#1189 CosmosClientSideRequestStatistics merged into DiagnosticContext
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/AddressResolutionStatistics.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/BackendMetricsExtractor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosClientSideRequestStatistics.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticScope.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsInternalVisitor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsInternalVisitor{TResult}.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/EmptyCosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/PointOperationStatistics.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/QueryPageDiagnostics.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/StoreResponseStatistics.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosExceptionFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosClientSideRequestStatistics.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/EncryptionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/BaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/CosmosDiagnosticsSerializerTests.TestPointOperationStatistics.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchOperationResultTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyBatchResponseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosExceptionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/BackendMetricsExtractorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/CosmosDiagnosticsSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PointOperationStatisticsTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Scenarios/GremlinScenarioTests.cs
  changelog.md
Labels: Diagnostics

#1257 vNext - CosmosClient constructor
  Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: VNext

#1258 vNext - DefaultSerializationOptions
  Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/azuredata/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: VNext, breaking

#1256 vNext - Remove CosmosClient.CosmosClientOptions
  Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: VNext

#1268 Add GetClientElapsedTime to CosmosDiagnostics
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticScope.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsCore.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsInternal.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/EmptyCosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Resource/DataEncryptionKey/DataEncryptionKeyCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedPartitionKeyResultSetIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/StandByFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserCore.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/BaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/CosmosDiagnosticsSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: Diagnostics, bug, feature

#1263 Fixed missing retry after for stream queries.
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  changelog.md
Labels: Internal team blocked, QUERY

#1274 CosmosClient now throws ObjectDisposedException
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedToken/ChangeFeedIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedToken/ReadFeedTokenIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
  changelog.md
Labels: bug

#1285 Add query plan diagnostics and refactor query diagnostics
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/QueryPageDiagnostics.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/Aggregate/AggregateDocumentQueryExecutionComponent.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/Aggregate/AggregateDocumentQueryExecutionComponent.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/Distinct/DistinctDocumentQueryExecutionComponent.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/Distinct/DistinctDocumentQueryExecutionComponent.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/GroupBy/GroupByDocumentQueryExecutionComponent.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/GroupBy/GroupByDocumentQueryExecutionComponent.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/SkipTake/SkipDocumentQueryExecutionComponent.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/SkipTake/SkipDocumentQueryExecutionComponent.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/SkipTake/TakeDocumentQueryExecutionComponent.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/SkipTake/TakeDocumentQueryExecutionComponent.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosCrossPartitionQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/ItemProducers/ItemProducer.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/ItemProducers/ItemProducerTree.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/LazyCosmosQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/OrderBy/CosmosOrderByItemQueryExecutionContext.Drain.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/Parallel/CosmosParallelItemQueryExecutionContext.Drain.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/PipelinedDocumentQueryExecutionContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryContext.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/QueryResponseCore.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryContextCore.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/MockCosmosQueryClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockRequestHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/BackendMetricsExtractorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockItemProducerFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
  changelog.md
Labels: Diagnostics, QUERY

#1304 Fixed project's XML documentation
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  changelog.md
Labels: bug, documentation

#1312 Compare case for default(PartitionKey)
  Microsoft.Azure.Cosmos/src/PartitionKey.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs
  changelog.md
Labels: bug

#1314 TCP endpoint rediscovery
  Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  changelog.md
Labels: feature

#1325 3.7.1-preview release notes
  Microsoft.Azure.Cosmos/Directory.Build.props
  changelog.md
Labels: Engineering
