Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-04, with the labels that each got.

#1322 [Internal] PR Requirements: Add PR title requirements to allow changelog generation
  .github/workflows/prlint.yml
  PULL_REQUEST_TEMPLATE.md
  azure-pipelines.yml
Labels: documentation

#1341 [vNext] PR Requirements: Add PR title requirements for changelog generation
  .github/workflows/prlint.yml
  PULL_REQUEST_TEMPLATE.md
  azure-pipelines-v4.yml
  azure-pipelines.yml
Labels: Engineering, VNext

#1347 Internal: Add 3.8.0 release notes
  Microsoft.Azure.Cosmos/contracts/API_3.8.0.txt
  changelog.md
Labels: Engineering

#1350 [Internal] API Version: Fix version for 3.8.0 release
  Microsoft.Azure.Cosmos/Directory.Build.props
Labels: Engineering

#1351 [Internal] Build: Add Independent version for Preview
  Microsoft.Azure.Cosmos/Directory.Build.props
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Labels: Engineering

#1363 [Internal] Documentation: (Fix) README example
  README.md
Labels: documentation

#1366 [Internal] Tests: Add retriable TestClass decorator
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAggregateFunctionsBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAttributeContractBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqSQLTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/RetriableTestClassAttributeTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/RetriableTestClass.cs
Labels: Engineering

#1371 Query: Fix malformed continuation token error message.
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
Labels: QUERY

#1372 [Internal] UniqueIndexTests: Fix to use CosmosClient instead of DocumentClient
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UniqueIndexTests.cs
Labels: Engineering, bug

#1367 [vNext] Documentation: Fix Obsolete member and fix classes comments
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/IndexingPolicy.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/UniqueKeyPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/Enums/OperationKind.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
Labels: VNext, documentation

#1384 [Internal] Documentation: Fix documentation example and links
  Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/UniqueKeyPolicy.cs
Labels: documentation

#1377 Autoscale Preview: Add to public preview release
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ThroughputProperties.cs
Labels: feature

#1388 [Internal] Documentation: Fix text on retry builder extension
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Labels: documentation

#1403 [Internal] Pipeline: Add Microsoft.Azure.Cosmos.Encryption release pipeline
  azure-pipelines-encryption.yml
Labels: Engineering

#1411 [Internal] Package: Add missing nuget required properties
  Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Labels: bug

#1410 [Preview] FeedRange: Add Json serialization support
  Microsoft.Azure.Cosmos/src/FeedRange/FeedRange.cs
  Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEPK.cs
  Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeInternal.cs
  Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKey.cs
  Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKeyRange.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Serializer/FeedRange/FeedRangeCompositeContinuationConverter.cs
  Microsoft.Azure.Cosmos/src/Serializer/FeedRange/FeedRangeEPKConverter.cs
  Microsoft.Azure.Cosmos/src/Serializer/FeedRange/FeedRangeInternalConverter.cs
  Microsoft.Azure.Cosmos/src/Serializer/FeedRange/FeedRangePartitionKeyConverter.cs
  Microsoft.Azure.Cosmos/src/Serializer/FeedRange/FeedRangePartitionKeyRangeConverter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/FeedRangeTests.cs
Labels: feature

#1425 [Internal] Performance: Fix namespace reference
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/CosmosElements/DeserializerBenchmark.cs
Labels: bug

#1426 [Internal] Build: Fix Performance project step
  templates/build-test.yml
Labels: Engineering

#1432 [Internal] Samples: Fix bulk migration time tracking
  Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs
Labels: Samples

#1433 [Internal] Samples: Fix Bulk migration tag
  Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs
Labels: Samples
