Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-12, with the labels that each got.

#2043 Internal Test: Fixes transient TestTokenCredentialBackgroundRefreshAsync failures
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosAuthorizationTests.cs
Labels: Engineering

#2042 Change Feed Processor: Fixes StartTime not being correctly applied. Introduced in PR #1933
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedStartFromRequestOptionPopulator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Labels: bug

#2041 Request Charge: Fixes request charges for offers and CreateIfNotExists APIs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosThroughputTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/RequestChargeHandlerHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/RequestHandlerHelper.cs
Labels: bug

#2045 [Internal] PRLint: Adds version 1.5
  .github/workflows/prlint.yml
Labels: Engineering

#2047 Diagnostics: Adds operation name to summary
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
Labels: Diagnostics

#2069 Bulk: Fixes incorrect routing on split
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperationContext.cs
  Microsoft.Azure.Cosmos/src/BulkPartitionKeyRangeGoneRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs
Labels: Bulk, bug

#2071 Diagnostics: Fixes substatuscode when recording internal DocumentClientException
  Microsoft.Azure.Cosmos/src/HttpClient/TransientHttpClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
Labels: Diagnostics

#2077 Availability: Fixes retry behavior on HttpException
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GlobalEndpointManagerTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/testhost.dll.config
Labels: bug

#2076 Documentation: Adds retry statements to exception document
  Exceptions.md
Labels: documentation

#1861 Client Encryption : Adds Support for Microsoft Data Encryption/MDE, its Encryption Algorithm and KeyWrap Provider Services.
  Microsoft.Azure.Cosmos.Encryption/src/Constants.cs
  Microsoft.Azure.Cosmos.Encryption/src/CosmosDataEncryptionKeyProvider.cs
  Microsoft.Azure.Cosmos.Encryption/src/CosmosEncryptionAlgorithm.cs
  Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKey.cs
  Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
  Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerInlineCore.cs
  Microsoft.Azure.Cosmos.Encryption/src/DekCache.cs
  Microsoft.Azure.Cosmos.Encryption/src/EncryptionKeyWrapMetadata.cs
  Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
  Microsoft.Azure.Cosmos.Encryption/src/EncryptionProperties.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/AzureKeyVaultKeyWrapMetadata.cs
  Microsoft.Azure.Cosmos.Encryption/src/KeyVault/AzureKeyVaultKeyWrapProvider.cs
  Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeCryptographyLib/Microsoft.Data.Encryption.Cryptography.dll
  Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeEncryptionAlgorithm.cs
  Microsoft.Azure.Cosmos.Encryption/src/MdeServices/MdeKeyWrapProvider.cs
  Microsoft.Azure.Cosmos.Encryption/src/MdeServices/README.md
  Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/KeyVaultAccessClientTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/LegacyEncryptionTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
  Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json
  Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/CosmosEncryptorTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/LegacyEncryptionProcessorTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/MdeEncryptionProcessorTests.cs
  Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Microsoft.Azure.Cosmos.Encryption.Tests.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Encryption.csproj
Labels: feature

#2094 Query: Adds fast timeouts and retries to query plan
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
  Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
  Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneHotPath.cs
  Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRetriableHotPath.cs
  Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosGatewayTimeoutTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs
Labels: Diagnostics
