Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-05, with the labels that each got.

#1451 [Internal] Caches: Fix cache synchronization on Change Feed migration
  Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKeyRange.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/FeedRangeTests.cs
Labels: bug

#1441 Transport: Add HttpClientFactory support
  Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptionsFeatures.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Labels: feature

#1445 Transport: Fix ServicePoint for WebAssembly
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
  Microsoft.Azure.Cosmos/src/Util/ServicePointAccessor.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ServicePointAccessorTests.cs
Labels: feature

#1453 ResponseFactory: Add a response factory to the public API
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryInternal.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs
Labels: feature

#1462 UserAgent: Fix feature tracking
  Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs
Labels: bug

#1471 [Internal] Pull Request: Fix the pull request title validation
  .github/workflows/prlint.yml
Labels: Engineering, VNext

#1470 [vNext] Contract: Fix iterators to Async rename
  Microsoft.Azure.Cosmos/azuredata/Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/azuredata/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
  Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Conflict/CosmosConflicts.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Database/CosmosDatabase.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Scripts/CosmosScripts.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/User/CosmosUser.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/User/UserCore.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/AsyncEnumerationTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/SmokeTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/QueryOracle.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/QueryOracleUtil.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
Labels: VNext, breaking

#1439 No content on Response: Add the ability to have operation return no content from Cosmos DB
  Microsoft.Azure.Cosmos/src/Batch/HybridRowBatchSchemas.json
  Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Labels: feature

#1492 [Internal] Contract: Add 3.9.0-preview3 contract
  Microsoft.Azure.Cosmos/contracts/API_3.9.0-preview3.txt
Labels: Engineering

#1493 [Internal] Changelog: Add 3.9.0 preview3 notes
  changelog.md
Labels: documentation

#1498 Documentation: Fix Database and ContainerProperties code comments
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/DatabaseProperties.cs
Labels: documentation

#1515 Performance: Fix MemoryStream with un-accesible buffer
  Microsoft.Azure.Cosmos/src/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/FeedRangeIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosElementSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: Performance, improvement

#1497 [vNext] TimeToLive: Fix name of DefaultTimeToLive to DefaultTimeToLiveInSeconds
  Microsoft.Azure.Cosmos/azuredata/Fluent/Settings/ContainerDefinition.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/CosmosContainerProperties.cs
  Microsoft.Azure.Cosmos/azuredata/Serializer/Settings/TextJsonContainerPropertiesConverter.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
Labels: VNext, breaking

#1495 [vNext] Monitoring: Add explicit headers
  Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Labels: Diagnostics, VNext

#1503 [vNext] Monitoring: Add Diagnostics.ApplicationId when ApplicationName is set
  Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Labels: VNext

#1516 Query and change feed: Add serialization optimization by using list instead of by item
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingWorkEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryInternal.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosElementSerializer.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosFeedResponseSerializer.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/CosmosElements/ReadFeedBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
Labels: Performance

#1521 [Internal] UserAgent: Fix ClientId generation
  Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/EnvironmentInformationTests.cs
Labels: bug

#1522 [Internal] Code maintenance: Add code cleanup and refactor
  .editorconfig
  Microsoft.Azure.Cosmos.sln
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchExecUtils.cs
  Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInternal.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInternal{T}.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator{T}.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedRangeIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
Labels: Engineering

#1535 [vNext] Contract: Fix remove Spatial classes
  Microsoft.Azure.Cosmos/azuredata/Serializer/CosmosTextJsonSerializer.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/BoundingBox.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/Crs.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/CrsType.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/Geometry.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/GeometryParams.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/GeometryShape.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/GeometryType.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/GeometryValidationResult.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/LineString.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/LinearRing.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/LinkedCrs.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/NamedCrs.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/Point.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/Polygon.cs
  Microsoft.Azure.Cosmos/azuredata/Spatial/Position.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/CommonSerializationTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/CrsTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/GeometryCollectionTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/LineStringTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/MultiLineStringTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/MultiPointTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/MultiPolygonTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/PointTest.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Spatial/PolygonTest.cs
Labels: VNext, breaking

#1424 [Internal] Tests: Add coverage report
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
  templates/build-test.yml
Labels: Engineering

#1539 Diagnostics: Fix ToString() to not grow exponentially with retries
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosClientSideRequestStatistics.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
Labels: Diagnostics, bug

#1542 [Internal] Tests: Fix EnvironmentTest to use Tasks instead of Parallel
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/EnvironmentInformationTests.cs
Labels: Engineering

#1564 EnableContentResponseOnWrite documentation: Fix documentation and add samples
  Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
Labels: documentation

#1489 RequestOptions: Add ability for applications to specify request context
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ReadFeedTokenTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchRequestPayloadReader.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Labels: discussion-wanted

#1577 [vNext] Contract: Fix Move SpatialPath to base namespace
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/IndexingPolicy.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Settings/SpatialPath.cs
  Microsoft.Azure.Cosmos/azuredata/Serializer/Settings/TextJsonSpatialPathConverter.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/Enums/SpatialType.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/IndexingPolicyEqualityComparer.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
Labels: VNext, breaking
