Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-06, with the labels that each got.

#1302 Diagnostics: Add Troubleshooting guide pages
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  TroubleshootingGuides/CosmosMacSignature.md
  TroubleshootingGuides/CosmosNotFound.md
  TroubleshootingGuides/CosmosNotModified.md
  TroubleshootingGuides/CosmosRequestHeaderTooLarge.md
  TroubleshootingGuides/CosmosRequestRateTooLarge.md
  TroubleshootingGuides/CosmosRequestTimeoutClient.md
  TroubleshootingGuides/CosmosRequestTimeoutService.md
  TroubleshootingGuides/CosmosSNATPortExhaustion.md
Labels: Diagnostics

#1588 [vNext] README: Add descriptive scenarios
  README.md
Labels: VNext, documentation

#1597 [vNext] Logging: Fix NotImplementedException while using ConsoleLogger
  Microsoft.Azure.Cosmos/azuredata/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Diagnostics/DiagnosticsScopeTests.cs
Labels: VNext, bug

#1599 [vNext] Documentation: Fix code samples
  Microsoft.Azure.Cosmos/azuredata/Resource/Container/CosmosContainer.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Database/CosmosDatabase.cs
Labels: VNext, documentation

#1602 Diagnostics: Add CPU history
  Microsoft.Azure.Cosmos/src/Diagnostics/BackendMetricsExtractor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsInternalVisitor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsInternalVisitor{TResult}.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosSystemInfo.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/EmptyCosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/DiagnosticsHandler.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Labels: Diagnostics

#1603 Documentation: Add exception handling document
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  TroubleshootingGuides/CosmosMacSignature.md
  TroubleshootingGuides/CosmosNotFound.md
  TroubleshootingGuides/CosmosNotModified.md
  TroubleshootingGuides/CosmosRequestHeaderTooLarge.md
  TroubleshootingGuides/CosmosRequestRateTooLarge.md
  TroubleshootingGuides/CosmosRequestTimeout.md
  TroubleshootingGuides/CosmosRequestTimeoutClient.md
  TroubleshootingGuides/CosmosRequestTimeoutService.md
  TroubleshootingGuides/CosmosServiceUnavailable.md
  TroubleshootingGuides/Exceptions.md
Labels: documentation

#1582 [Internal] Conflicts: Fix conflicts should use the FeedRangeIterator
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedRangeIteratorCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/ReadFeedTokenIteratorCoreTests.cs
Labels: bug

#1621 [Internal] Documentation: Fix version on README
  README.md
Labels: VNext

#1587 Diagnostics: Add synchronization context Part 1
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosClientSideRequestStatistics.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsCore.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/EmptyCosmosDiagnosticsContext.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/QueryResponses/StandByFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ThroughputProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockCosmosUtil.cs
Labels: Diagnostics

#1612 [Internal] Performance: Add TimerWheel implementation
  Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheel.cs
  Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheelCore.cs
  Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheelTimer.cs
  Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheelTimerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/TimerBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/TimerWheel/Utils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelTimerCoreTests.cs
Labels: Performance

#1638 Documentation & Samples: Add IDisposable to all examples & other improvements
  Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/Handlers/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/UserManagement/UserManagementProgram.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator{T}.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/Permission.cs
  Microsoft.Azure.Cosmos/src/Resource/Response.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/UserDefinedFunctionProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/User/User.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
  README.md
Labels: documentation

#1631 [vNext] Fluent: Fix fluent chain usage
  Microsoft.Azure.Cosmos/azuredata/Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs
  Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/azuredata/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/azuredata/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/azuredata/Fluent/Settings/ContainerDefinition.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Database/CosmosDatabase.cs
  Microsoft.Azure.Cosmos/azuredata/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/CompositeIndexDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ConflictResolutionDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/IndexingPolicyDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/PathsDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/SpatialIndexDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/UniqueKeyDefinition.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/CompositeIndexDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/ConflictResolutionDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/IndexingPolicyDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/PathsDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/SpatialIndexDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/UniqueKeyDefinitionTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/MockCosmosUtil.cs
Labels: VNext, breaking

#1639 CosmosClient: Add check for empty keys
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs
Labels: bug

#1629 [Internal] README: Fix optimistic concurrency sample
  README.md
Labels: VNext, documentation

#1645 [internal] Contracts: Add dependency contract and codowners
  CODEOWNERS
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DirectContractTests.cs
Labels: Engineering

#1643 Diagnostics: Add synchronization context Part 2 for Container
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Labels: Diagnostics

#1640 Bulk: Add TimerWheel to Bulk to improve latency
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncStreamer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
Labels: Bulk, Performance

#1666 CosmosOperationCanceledException: Fix handler to catch all operation cancelled exceptions
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs
Labels: Diagnostics

#1667 Diagnostics: Add synchronization context Part 3 for remaining types
  Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserCore.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserInlineCore.cs
Labels: Diagnostics
