Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-11, with the labels that each got.

#1977 Performance diagnostics: Adds static timer and caches handler name
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticScope.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/RequestHandlerScope.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/RouterHandler.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: Performance

#1983 Internal Headers: Fixes ExtractResponseHeaders
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
Labels: Internal team blocked

#1982 Internal Gates: Adds memory allocation gates to check-ins
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Program.cs
  templates/build-test.yml
Labels: Engineering

#1999 [Internal] Performance: Fixes exception serialization when tracing is not enabled
  Microsoft.Azure.Cosmos/src/ResourceThrottleRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResourceThrottleRetryPolicyTests.cs
Labels: Performance

#2002 [Internal] Transport: Adds EPK headers serialization
  Directory.Build.props
Labels: Transport

#2016 Performance: Fixes lock contentions and reduce allocations on TCP requests
  Directory.Build.props
Labels: Performance

#2025 Preview GetFeedRangesAsync: Fixes null ref exception caused by stale cache
  Microsoft.Azure.Cosmos/src/ChangeFeed/StandByFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKeyRangeExtractor.cs
  Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Contracts/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs
Labels: bug

#2028 [Internal] Bulk: Adds retry on CompletingSplit
  Microsoft.Azure.Cosmos/src/BulkPartitionKeyRangeGoneRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs
Labels: Bulk
