Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-07, with the labels that each got.

#1676 [vNext] Contract: Add CosmosClientOptions constructor for ApplicationName
  Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/azuredata/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/azuredata/Serializer/JsonEncodedStrings.cs
  Microsoft.Azure.Cosmos/azuredata/Serializer/TextJsonCosmosClientOptionsConverter.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
Labels: VNext, breaking

#1682 Performance: Fix CPU consumption with EnableTcpConnectionEndpointRediscovery
  Microsoft.Azure.Cosmos/Directory.Build.props
  Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RequestEventHandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StoreReaderTest.cs
Labels: Performance

#1689 [Internal] HeadersValidationTests: Fix CI and sync to master version
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
Labels: Engineering, bug

#1695 Docs: Add specific TSGs for 408 scenarios
  TroubleshootingGuides/CosmosDotNetRequestTimeout.md
  TroubleshootingGuides/CosmosServiceRequestTimeout.md
Labels: documentation

#1569 Batch API: Add support of request options for transactional batch
  Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
  Microsoft.Azure.Cosmos/src/Batch/PartitionKeyRangeBatchResponse.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatch.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: API_REVIEW

#1699 [Internal] PR Lint: Fixes to use new title regex
  .github/workflows/prlint.yml
  PULL_REQUEST_TEMPLATE.md
Labels: Engineering

#1704 [Internal] PR Lint: Fixes the yaml file
  .github/workflows/prlint.yml
Labels: Engineering

#1616 [Internal] Patch: Adds internal JSON Patch support
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatch.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Patch/PatchConstants.cs
  Microsoft.Azure.Cosmos/src/Patch/PatchOperation.cs
  Microsoft.Azure.Cosmos/src/Patch/PatchOperationCore.cs
  Microsoft.Azure.Cosmos/src/Patch/PatchOperationCore{T}.cs
  Microsoft.Azure.Cosmos/src/Patch/PatchOperationType.cs
  Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs
  Microsoft.Azure.Cosmos/src/Patch/PatchOperation{T}.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosSerializerCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PatchOperationTests.cs
  templates/emulator-setup.yml
Labels: API_REVIEW

#1715 Availability: Adds cross-region retry mechanism on transient connectivity issues
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Labels: improvement

#1720 Gateway Trace: Fixes a bug where the ActivityId is being set to Guid.Empty
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Labels: bug

#1731 [Internal] Projects: Fixes all project to use LTS .NET core versions
  Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
  Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Microsoft.Azure.Cosmos.Encryption.Tests.csproj
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Shared/Shared.csproj
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Labels: Engineering

#1733 Change Feed Processor: Adds backward compatibility of lease store
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
Labels: ChangeFeed

#1740 Connection limits: Fixes .NET core to honor gateway connection limit
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Labels: bug

#1728 Diagnostics: Adds ActivityScope to operation level
  Microsoft.Azure.Cosmos/src/ActivityScope.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
Labels: Diagnostics

#1658 [Internal] Subpartitioning: Adds SDK changes to support subpartitioning.
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/PartitionKey.cs
  Microsoft.Azure.Cosmos/src/PartitionKeyBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  templates/emulator-setup.yml
Labels: API_REVIEW
