Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2020-09, with the labels that each got.

#1825 RequestOptions.Properties: Adds new feature to public SDK
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: feature

#1835 HttpClient: Adds optimization to avoid double buffering response
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
Labels: Performance

#1863 Blazor: Fixes not supported HTTP features
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
Labels: bug

#1875 HttpClient: Fixes HttpResponseMessage.RequestMessage is null in WASM
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs
Labels: bug

#1882 Performance: Adds SessionContainer optimizations and style fixes
  Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
  Microsoft.Azure.Cosmos/src/SessionContainer.cs
Labels: Performance

#1885 [Internal] Tests: Fixes CFP tests not stopping
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs
Labels: Engineering

#1887 [Internal] TimerWheel: Fixes tests to avoid flakyness
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelCoreTests.cs
Labels: Engineering

#1886 Change Feed Processor: Fixes failures during initialization
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseStoreCosmosTests.cs
Labels: ChangeFeed, bug

#1830 Change Feed Estimator: Adds support for detailed estimation per lease in PREVIEW
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Bootstrapping/PartitionSynchronizerCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorRunner.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorState.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/EqualPartitionsBalancingStrategy.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingLeaseTokenWork.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingWorkEstimator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/RemainingWorkEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedEstimatorDispatcher.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverContext.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedEstimator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedEstimatorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedEstimatorRunner.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseStoreManager.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseStoreManagerBuilder.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/ChangeFeedEstimatorRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorRunnerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorBuilderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/EqualPartitionsBalancingStrategyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedEstimatorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedEstimatorRunnerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerSplitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSupervisorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/RemainingWorkEstimatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Labels: ChangeFeed
