Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2021-02, with the labels that each got.

#2122 [Preview] Change Feed: Adds Full Fidelity support
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedMode.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: ChangeFeed, feature

#2186 Documentation: Fixes several documentation errors
  Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
Labels: documentation

#2170 Change Feed Processor: Adds detailed estimator APIs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorState.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/ChangeFeedEstimatorRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: ChangeFeed

#2198 CosmosClientOptions: Fixes a bug causing ConsistentPrefix to be convert to BoundedStaleness
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Labels: bug

#2251 [Internal] CTL: Fixes project references
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CosmosCTL.csproj
Labels: bug
