Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2021-01, with the labels that each got.

#2099 CosmosDiagnostics: Fixes IndexOutOfRangeException
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryContextCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
Labels: Diagnostics, bug

#2098 Gateway: Adds header optimization
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/Headers/Headers.cs
  Microsoft.Azure.Cosmos/src/Headers/HttpResponseHeadersWrapper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HttpResponseHeadersWrapperTests.cs
Labels: Performance

#2020 [Internal] Change Feed: Adds change feed retention policy to container configuration
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ConflictResolutionDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: API_REVIEW, ChangeFeed

#1490 PartitionKeyDelete: Adds API to delete all items in a partition key
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Labels: API_REVIEW

#2110 CosmosException: Fixes substatuscode to get the correct value instead of 0 when it is not in the enum.
  Microsoft.Azure.Cosmos/src/Headers/Headers.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosExceptionFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/HttpHandlerHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosExceptionTests.cs
Labels: bug

#2109 [Internal] Change Feed: Adds Full Fidelity support
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedCrossFeedRangeAsyncEnumerable.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedMode.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedModeFullFidelity.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedModeIncremental.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedPartitionRangePageAsyncEnumerator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/CrossPartitionChangeFeedAsyncEnumerator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/IChangeFeedDataSource.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/IMonadicChangeFeedDataSource.cs
  Microsoft.Azure.Cosmos/src/Pagination/DocumentContainer.cs
  Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/ChangeFeedAsyncEnumerableTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Contracts/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/EndToEnd.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/CrossPartitionChangeFeedAsyncEnumeratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentContainerChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/NetworkAttachedDocumentContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/CosmosVirtualUnitTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/ChangeFeedIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/DocumentContainerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/FlakyDocumentContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/EndToEndTraceTests.cs
Labels: feature

#2123 Availability: Fixes read session not available retries on multi master accounts
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Labels: bug

#2124 Bulk: Adds retry on RequestEntityTooLarge
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
  Microsoft.Azure.Cosmos/src/BulkExecutionRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs
Labels: Bulk

#2134 [Internal] CTL: Adds CTL project and ReadWriteQuery workload
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLConfig.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLOperationHandler.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLResultProducer.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CosmosCTL.csproj
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CosmosCTL.sln
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Program.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ICTLScenario.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadWriteQueryScenario.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Utils.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/WorkloadType.cs
  azure-pipelines.yml
  templates/build-ctl.yml
Labels: Engineering

#2143 [Internal] CTL: Adds Dockerfile to produce a docker image to run
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Dockerfile
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/run_ctl.sh
Labels: Engineering

#2148 [Internal] CTL: Adds yml automation for daily image build
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Dockerfile
  azure-pipelines-ctl-publishing.yml
  templates/build-ctl.yml
Labels: Engineering

#2152 [Internal] Emulator Tests: Refactors the ToDoActivity object to use pk instead of status
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/ChangeFeedAsyncEnumerableTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Contracts/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosGatewayTimeoutTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHeaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosOperationCanceledExceptionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/FeedRangeTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ReadFeedTokenTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ReadFeed/ReadFeedAsyncEnumerableTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/ToDoActivity.cs
Labels: Engineering

#2159 Documentation: Fixes ConnectionMode intellisense
  Microsoft.Azure.Cosmos/src/ConnectionMode.cs
Labels: documentation

#2161 [Internal] CTL: Adds Change Feed Processor scenario
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLConfig.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Program.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedProcessorScenario.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ICTLScenario.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadWriteQueryScenario.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/WorkloadType.cs
Labels: Engineering
