Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2022-03, with the labels that each got.

#3057 [INTERNAL] Pipeline: Adds SBOM generation
  azure-pipelines-encryption-custom.yml
  azure-pipelines-encryption.yml
  azure-pipelines-official.yml
Labels: Engineering

#3073 Documentation: Refactors WithInstanceName documentation
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
Labels: documentation

#3101 Documentation: Adds remarks for different APIs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Labels: documentation

#3112 Documentation: Fixes connectionstring example
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
Labels: documentation

#3124 Change Feed Processor: Fixes noisy error notification when lease is stolen by other host
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerTests.cs
Labels: bug, ChangeFeed
