Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2022-01, with the labels that each got.

#2937 Session: Fixes scoped session token on partition splits and multiple write endpoints enabled
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewaySessionTokenTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Labels: bug

#2965 Session: Fixes token being sent if request had a different consistency level on Gateway mode
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Labels: bug

#2980 Session: Fixes Gateway session scope during merges
  Microsoft.Azure.Cosmos/src/SessionContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SessionContainerTest.cs
Labels: bug

#3000 Documentation: Fixes change feed estimator remarks
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimator.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorState.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Labels: documentation, ChangeFeed

#3004 Client Telemetry: Adds Thread Starvation Information
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
  Microsoft.Azure.Cosmos/src/Telemetry/MetricInfo.cs
  Microsoft.Azure.Cosmos/src/Telemetry/SystemInfo.cs
  Microsoft.Azure.Cosmos/src/Telemetry/TelemetrySystemUsage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Labels: Telemetry
