Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2023-05, with the labels that each got.

#3833 Query: Adds TRIM string system function support in LINQ
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestStringFunctions.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
Labels: auto-merge

#3832 Query: Fixes Parsing Error in SQL DOM when CultureInfo is available
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/CstToAstVisitor.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Parser/SqlParserBaselineTests.cs
Labels: auto-merge

#3809 Client Encryption: Adds api FetchDataEncryptionKeyWithoutRawKeyAsync and FetchDataEncryptionKeyAsync to get DEK without and with raw key respectively.
  Directory.Build.props
  Microsoft.Azure.Cosmos.Encryption.Custom/changelog.md
  Microsoft.Azure.Cosmos.Encryption.Custom/src/CosmosDataEncryptionKeyProvider.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/src/CosmosEncryptor.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/src/DataEncryptionKeyContainerCore.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/src/DataEncryptionKeyProvider.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/src/MdeServices/MdeEncryptionAlgorithm.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/EmulatorTests/LegacyEncryptionTests.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/EmulatorTests/MdeCustomEncryptionTests.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests/CosmosEncryptorTests.cs
Labels: auto-merge

#3826 Query : Adds support for Lambda expression reuse in LINQ expressions
  Microsoft.Azure.Cosmos/src/Linq/TranslationContext.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/BaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestLambdaReuse.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Labels: auto-merge

#3761 Query: Adds Computed Property SDK Support
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ComputedPropertiesDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ComputedProperty.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ComputedPropertyComparer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ComputedPropertyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: auto-merge

#3818 [Internal] Samples: Adds OpenTelemetry and Application Insights samples
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/AppSettings.json
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/AppSettings.json
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs
Labels: auto-merge

#3724 Query: Added remaining Cosmos Type checking functions to CosmosLinqExtensions
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/TypeCheckFunctions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestTypeCheckFunctions.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#3841 [Internal] Samples: Fixes OpenTelemetry and Application Insights samples
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs
Labels: auto-merge

#3847 PackageLicense: Removes PackageLicenseUrl and Adds PackageLicenseFile since PackageLicenseUrl is deprecated
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Labels: auto-merge

#3854 Full Fidelity Change Feed: Adds LatestVersion to ChangeFeedMode
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedMode.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#3845 AI Integration: Fixes Operation Name in the activity and end to end Tests.
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomOtelExporter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/Util.cs
Labels: Telemetry, AI Integration, auto-merge

#3855 SDK 3.34.0 : Adds version bump and changelog
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.34.0-preview.txt
  Microsoft.Azure.Cosmos/contracts/API_3.34.0.txt
  changelog.md
Labels: auto-merge

#3864 NugetPackage: Removes ThirdPartyNotice.txt from content and contentFiles folders
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Labels: auto-merge

#3860 Documentation: Adds see also link to Container.CreateTransactionalBatch
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatch.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Labels: auto-merge

#3852 Query: Adds type-markers with count and length for large arrays
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
Labels: QUERY, auto-merge

#3858 [Internal] AI Integration or Open Telemetry: Design Document
  docs/SdkDesign.md
Labels: Telemetry, auto-merge

#3838 Benchmarking: Adds use of ARM Templates for benchmarking
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/arm1.png
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/arm2.png
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/arm3.png
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/benchmarkTemplate.json
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/parameters.json
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/run.sh
Labels: auto-merge

#3875 [Internal] Benchmarking: Fixes URL Typo in Deploy To Azure Button
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
Labels: auto-merge

#3877 Direct Package Upgrade 3.31.0: Refactors code to make compatible with latest direct
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Regions.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/Util.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#3836 [Preview] Integrated cache: Adds BypassIntegratedCache to DedicatedGatewayRequestOptions
  Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Resource/Settings/DedicatedGatewayRequestOptionsTests.cs
Labels: auto-merge
