Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2023-03, with the labels that each got.

#3736 [Internal] Build: Fixes static tool analysis versions
  templates/static-tools.yml
Labels: Engineering

#3717 [Internal] ClientTelemetry: Adds logic to limit payload size to 2 MB
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryPayloadWriter.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
  Microsoft.Azure.Cosmos/src/Telemetry/Models/ClientTelemetryProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryPayloadWithoutMetrics.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryTests.cs
Labels: Telemetry

#3775 Change Feed Processor: Fixes LeaseLostException leaks on notification APIs for Renew scenarios
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManagerCosmos.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseManagerCosmosTests.cs
Labels: bug

#3768 Upgrade Resiliency: Refactors GatewayAddressCache to Mark TransportAddresses to Unhealthy when Connection Reset Event Occurs
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceTests.cs
Labels: .NET v3 SDK, Upgrade Resiliency
