Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2023-10, with the labels that each got.

#4078 Query: Adds LINQ RegexMatch Extension method
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/BuiltinFunctionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlFunctionCallScalarExpression.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestRegexMatchFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestStringCompare.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#4103 [Internal] LocalQuorum: Fixes request level consistency from Bounded to Strong on documentation
  docs/LocalQuorum.md
Labels: auto-merge

#4056 Client Telemetry: Adds new public APIs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/run.sh
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLConfig.cs
  Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosClientTelemetryOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosThresholdOptions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbEventSource.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/DistributedTracingOptions.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/Filters/DiagnosticsFilterHelper.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
  Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryConfigurationTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/DiagnosticHandlerHelperTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/DiagnosticsFilterHelperTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockCosmosUtil.cs
Labels: Telemetry, auto-merge

#4109 Benchmark: Fixes to show estimated cost of a container only when new container is getting created
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Program.cs
Labels: auto-merge

#4108 [Query][Internal]: Reverts adding new system strings in JsonBinaryEncoding
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.FirstValueOffsets.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.NodeTypes.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.StringLengths.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.SystemStrings.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.SystemStrings.tt
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.TypeMarker.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.ValueLengths.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
Labels: QUERY, auto-merge

#4016 CosmosClientOptions: Adds support for multiple formats of Azure region names
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/RegionNameMapper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Labels: auto-merge

#4111 Distributed Tracing: Fixes traceid null exception issue
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DistributedTracingOTelTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomOtelExporter.cs
Labels: auto-merge

#4117 Telemetry Options: Adds telemetry options in GA package
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosClientTelemetryOptions.cs
  Microsoft.Azure.Cosmos/src/CosmosThresholdOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#4120 [Internal] Direct Package: Adds version bump
  Directory.Build.props
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
Labels: auto-merge

#4127 Query : Adds Missing QueryMetrics Documentation
  Microsoft.Azure.Cosmos/src/Query/Core/Metrics/ServerSidePartitionedMetrics.cs
Labels: QUERY, auto-merge

#4119 TriggerOperation: Adds Upsert Operation Support
  Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerOperation.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: auto-merge

#4130 Release 3.36.0: Fixes pipeline by removing ReleasePackage variable
  azure-pipelines-official.yml
Labels: auto-merge

#4131 Release 3.36.0: Fixes pipeline by removing ReleasePackage variable (#…
  azure-pipelines-official.yml
Labels: auto-merge

#4125 Item Operations: Fixes JsonSerialization exception when MissingMemberHandling = Error on Json default settings when NotFound on Item operations.
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosExceptionFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: auto-merge

#4133 Release 3.36.0: Fixes Client Telemetry Integration test
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
  azure-pipelines-official.yml
Labels: auto-merge

#4114 [Internal] Query : Adds test coverage for custom serializers
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosLinqSerializerOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationWithCustomSerializerBaseline.TestMemberInitializerDataMember.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationWithCustomSerializerBaseline.TestMemberInitializerDotNet.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationWithCustomSerializerBaseline.TestMemberInitializerMultiSerializer.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationWithCustomSerializerBaseline.TestMemberInitializerNewtonsoft.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationWithCustomSerializerBaseline.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Labels: QUERY

#4137 Release 3.36.0: Fixes Client Telemetry Integration test (#4133)
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
  azure-pipelines-official.yml
Labels: auto-merge

#4132 Release 3.36.0 : Fixes Client Telemetry Release Test
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
  azure-pipelines-official.yml
Labels: auto-merge

#4141 [Internal] Query: Fixes flaky test
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: QUERY, auto-merge

#4144 [Internal] Query: Fixes flaky test
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: auto-merge

#4145 [Internal] Query: Fixes flaky test
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: auto-merge

#4146 [Internal] Query: Removes Ode changes which rejected certain types of queries which were previously supported on 3.36.0
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
Labels: auto-merge

#4142 [Internal] Query: Removes Ode changes which rejected certain types of queries which were previously supported on 3.36.0-preview
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
Labels: auto-merge

#4149 Release 3.36.0: Fixes client config test and preview pipeline
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
  azure-pipelines-official.yml
Labels: auto-merge

#4148 Release 3.36.0: Fixes Preview Pipeline and Client Config Test
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
  azure-pipelines-official.yml
Labels: auto-merge

#4150 Release 3.36.0: Fixes client config test and preview pipeline (#4149)
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
  azure-pipelines-official.yml
Labels: auto-merge

#4100 Query : Fixes querying conflicts
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/ConflictsE2ETest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
Labels: auto-merge

#4155 Documentation: Fixes changelog typo and date
  changelog.md
Labels: auto-merge

#4073 Per Partition Automatic Failover: Fixes Gateway 503 Cold Start Issue
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/RetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
  Microsoft.Azure.Cosmos/src/Routing/IGlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerUnitTests.cs
  docs/PerPartitionAutomaticFailoverDesign.md
Labels: auto-merge, PerPartitionAutomaticFailover

#4158 [Internal] Query: Fixes optimalPageSize logic for OFFSET LIMIT in ORDER BY queries
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Labels: auto-merge

#4161 [Internal] Client Telemetry: Adds telemetry contract
  CODEOWNERS
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/ContractEnforcement.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/ContractEnforcementTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKTelemetryAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
  UpdateContracts.ps1
Labels: auto-merge
