Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2023-08, with the labels that each got.

#4004 Query: Refactors changelog.md with Optimistic Direct Execution recommendation
  changelog.md
Labels: auto-merge

#3839 [Internal] Query: Adds performance testing for OptimisticDirectExecution pipeline
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/ContentSerializationPerformanceTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/OptimisticDirectExecutionPerformanceTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/QueryStatisticsMetrics.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/settings.json
Labels: QUERY, auto-merge

#4009 Query: Adds ODE continuation token support for non-ODE pipelines
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/OptimisticDirectExecution/OptimisticDirectExecutionContinuationToken.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
Labels: QUERY, auto-merge

#4019 [Internal] Upgrade Resiliency: Refactors Code to Disable Replica Validation Feature in Preview
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Labels: auto-merge

#4024 3.35.3: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.35.3-preview.txt
  Microsoft.Azure.Cosmos/contracts/API_3.35.3.txt
  changelog.md
Labels: auto-merge

#4021 [Internal] Distributed tracing: Adds a sample to collect activities and events using custom listener
  Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
  Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/CustomDiagnosticAndEventListener.cs
  Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/CustomDiagnosticAndEventListener.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/Program.cs
Labels: Telemetry, auto-merge

#4030 Upgrade Resiliency: Fixes Race Condition by Calling Dispose Too Early.
  Directory.Build.props
Labels: Upgrade Resiliency, auto-merge, gallium-semester

#4032 [Internal] Change Log: Fixes Change Log to Reflect Correct Items for Release `3.35.3`
  changelog.md
Labels: auto-merge

#4026 [Hotfix] Upgrade Resiliency: Refactors Code to Disable Replica Validation Feature in Preview
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.35.3-preview.txt
  Microsoft.Azure.Cosmos/contracts/API_3.35.3.txt
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  changelog.md
Labels: auto-merge

#4025 [Hotfix] Upgrade Resiliency: Refactors Code to Disable Replica Validation Feature in Preview
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.35.3-preview.txt
  Microsoft.Azure.Cosmos/contracts/API_3.35.3.txt
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  changelog.md
Labels: auto-merge

#4031 Documentation: Fixes article links (replaced links V2 to V3 SDK version) + Azure Cosmos DB typo
  Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RetryOptions.cs
Labels: documentation, auto-merge

#3950 [Internal] Benchmark tool: Adds Cosmos Benchmark Metrics
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/IExecutionStrategy.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/IExecutor.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/IMetricsCollector.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/MetricsCollector.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/MetricsCollectorProvider.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/ParallelExecutionStrategy.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/SerialOperationExecutor.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/TelemetrySpan.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/MetricCollectionWindow.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Program.cs
Labels: auto-merge

#4039 GatewayAddressCache: Fixes Unobserved Exception During Background Address Refresh
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Labels: auto-merge

#4037 [Internal] Client Telemetry: Refactors code for collectors
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
  Microsoft.Azure.Cosmos/src/Handler/TelemetryHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
  Microsoft.Azure.Cosmos/src/Telemetry/Collector/ITelemetryCollector.cs
  Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollector.cs
  Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollectorNoOp.cs
  Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryInformation.cs
  Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
  Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockCosmosUtil.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs
Labels: Telemetry, auto-merge

#3926 [Internal] Benchmark tool: Adds requests diagnostic data capture and upload to storage
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/arm1.png
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/arm2.png
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/arm3.png
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/benchmarkTemplate.json
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/parameters.json
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/run.sh
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/README.md
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/azuredeploy.json
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/scripts/custom-script.sh
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/scripts/execute.sh
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/system/cloud-init.txt
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkLatencyEventSource.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkProgress.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/DiagnosticDataListener.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/MetricsCollector.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/MetricsCollectorProvider.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/ParallelExecutionStrategy.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/SerialOperationExecutor.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/TelemetrySpan.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Program.cs
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/README.md
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Utility.cs
  Microsoft.Azure.Cosmos.Samples/Tools/CosmosBenchmarkTests/CosmosBenchmarkTests.csproj
  Microsoft.Azure.Cosmos.Samples/Tools/CosmosBenchmarkTests/Fx/DiagnosticDataListenerTests.cs
Labels: auto-merge

#4053 [Internal] Benchmark tool: Adds feature to the dashboard that generate plots queries for metrics with a workload name prefix, depending on the benchmark workload type. #4048
  Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/azuredeploy.json
Labels: auto-merge
