Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2023-11, with the labels that each got.

#4160 [Internal] Query: Removes ForcePassThrough support
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Labels: QUERY, auto-merge

#4123 [Internal] Upgrade Resiliency: Fixes Duplicate Channel and Task Creation.
  Microsoft.Azure.Cosmos/src/Routing/AsyncCacheNonBlocking.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBadReplicaTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/MockSetupsHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/AsyncCacheNonBlockingTests.cs
Labels: Upgrade Resiliency, auto-merge

#4167 [Internal] DocumentClient: Adds TryGetAccountProperties
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/InterfaceParityTest.cs
Labels: auto-merge

#4170 Query: Fixes documentation to reflect state of System.Text.Json serializer
  Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/Program.cs
Labels: QUERY, auto-merge

#4163 [Internal] Query: Adds interface for linq serialization functions
  Microsoft.Azure.Cosmos/src/Linq/CosmosElementToSqlScalarExpressionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/DefaultCosmosLinqSerializer.cs
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Linq/ICosmosLinqSerializer.cs
  Microsoft.Azure.Cosmos/src/Linq/QueryUnderConstruction.cs
  Microsoft.Azure.Cosmos/src/Linq/SQLTranslator.cs
  Microsoft.Azure.Cosmos/src/Linq/TranslationContext.cs
  Microsoft.Azure.Cosmos/src/Linq/TypeSystem.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqAttributeContractBaselineTests.cs
Labels: QUERY, auto-merge

#4128 Routing: Adds ExcludeRegions Feature to RequestOptions
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Labels: auto-merge

#4180 Upgrade Resiliency: Adds Code to Enable Advanced Replica Selection Feature for Preview
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Labels: Upgrade Resiliency, auto-merge

#4185 [Internal] Security: Fixes NuGetAudit fail on VS 17.8 for Newtonsoft 10.0.2
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Labels: auto-merge

#4186 Documentation: Adds Upsert documentation to include status codes for Created vs Replaced
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Labels: auto-merge

#4188 [Internal] Code Analysis: Fixes all warning in source/test/usage projects
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/Program.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/StopwatchAllocationsBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ServicePointAccessorTests.cs
Labels: auto-merge

#4191 3.37.0: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.37.0-preview.txt
  Microsoft.Azure.Cosmos/contracts/API_3.37.0.txt
  changelog.md
Labels: auto-merge

#4192 [Internal] Versioning: Adds guidance for versioning SDK releases
  README.md
  docs/versioning.md
Labels: Engineering, auto-merge
