Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2023-12, with the labels that each got.

#4176 [Internal] Query: Adds Baseline test for exceeding header length for index advisor
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/IndexMetricsParserBaselineTest.IndexUtilizationHeaderLengthTest.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Labels: auto-merge

#4122 Query: Add Optimistic Direct Execution configuration override support on the Client
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OptimisticDirectExecutionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Labels: QUERY, auto-merge

#4177 [Internal] Query: Adds ClientQL Compatibility Level support on client
  Microsoft.Azure.Cosmos/src/Query/Core/DistributionPlanSpec.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/ParallelCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/DCount/DCountQueryPipelineStage.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/DCount/DCountQueryPipelineStage.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Distinct/DistinctQueryPipelineStage.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Distinct/DistinctQueryPipelineStage.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/GroupBy/GroupByQueryPipelineStage.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/GroupBy/GroupByQueryPipelineStage.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/OptimisticDirectExecution/OptimisticDirectExecutionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Pagination/QueryPage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Skip/SkipQueryPipelineStage.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Skip/SkipQueryPipelineStage.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/SkipEmptyPageQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Take/TakeQueryPipelineStage.Client.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Take/TakeQueryPipelineStage.Compute.cs
  Microsoft.Azure.Cosmos/src/Query/Core/SqlQuerySpec.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/ReadFeed/ReadFeedCrossFeedRangeAsyncEnumerator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/FlakyDocumentContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ContinuationTokens/OrderByQueryResultTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Binary/BinarySample.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/AggregateEnumerable.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/ArrayCreateScalar.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/BinaryScalar.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/Distinct-SelectEnumerable.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/GroupByEnumerable.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/LiteralScalar.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/SelectManyEnumerable.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/SimpleEnumerable.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/SystemFunctionCallScalar.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/DistributionPlans/Text/TakeEnumerable.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/AggressivePrefetchPipelineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/MockQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/OrderByCrossPartitionQueryPipelineStageTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/SkipEmptyPageQueryPipelineStageTests.cs
Labels: QUERY, auto-merge

#4216 [Internal] CTL: Fixes docker image version dependency
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/CosmosCTL.csproj
  Microsoft.Azure.Cosmos.Samples/Tools/CTL/Dockerfile
Labels: Engineering

#4218 Distributed Tracing: Refactors Samples to use latest cosmosdb SDK
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs
Labels: auto-merge

#4214 Client Encryption: Adds Microsoft.Azure.Cosmos compatibility to version 3.35.4
  Directory.Build.props
  Microsoft.Azure.Cosmos.Encryption/changelog.md
  Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Labels: auto-merge

#4220 Change Feed Processor: Fixes disposal of unused CancellationTokenSource
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerSplitTests.cs
Labels: auto-merge

#4205 [Internal] Per Partition Automatic Failover: Fixes Metadata Requests Retry Policy
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
  Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSynchronizerCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MetadataRequestThrottleRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeCacheTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs
Labels: auto-merge, PerPartitionAutomaticFailover

#4226 [Internal] GlobalEndpointManager: Fixes Memory Leak
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Labels: auto-merge
