Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2024-09, with the labels that each got.

#4661 [Internal] FaultInjection: Fixes Test Project File
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionTests.csproj
Labels: auto-merge

#4687 Direct Package Upgrade: Fixes `Cosmos.Direct` Package to `3.36.0`
  Directory.Build.props
Labels: auto-merge

#4684 Hedging: Fixes Typo (WithAvailibilityStrategy -> WithAvailabilityStrategy) in CosmosClientBuilder
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Labels: auto-merge

#4694 [INTERNAL] Changelog: Adds note about Newtonsoft.Json (10.0.3) security vulnerability and upgrade to latest patched version
  changelog.md
Labels: auto-merge

#4643 Open Telemetry: Fixes Operation name to follow Otel convention
  Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchInternal.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeed/StandByFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/ReadFeed/ReadFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
  Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore{T}.cs
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator{T}.cs
  Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsInlineCore.cs
  Microsoft.Azure.Cosmos/src/Resource/User/UserInlineCore.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributes.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryConstants.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse{T}.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorIteratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedPartitionKeyResultSetIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/ChangeFeedIteratorCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/OpenTelemetryRecorderTests.cs
Labels: Telemetry, auto-merge

#4698 SDK 3.43.1 : Adds version bump and changelog
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.43.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.44.0-preview.1.txt
  changelog.md
Labels: auto-merge

#4680 INTERNAL Range: Fixes Range serialization to include minInclusive and maxInclusive
  Microsoft.Azure.Cosmos/src/Routing/RangeJsonConverter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/FeedRangeTests.cs
Labels: auto-merge

#4707 3.43.1: Adds cherry-picks to hotfix release branch
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.43.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.44.0-preview.1.txt
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/IGlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  changelog.md
Labels: auto-merge

#4693 [INTERNAL] Samples: Fixes upgrades to latest versions (vulnerabilities) and also warnings
  Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/BulkExecutorMigration.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/BulkSupport/BulkSupport.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelAllVersionsAndDeletesMode/CFPullModelAllVersionsAndDeletesMode.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelLatestVersionMode/CFPullModelLatestVersionMode.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeedAllVersionsAndDeletes/ChangeFeedAllVersionsAndDeletes.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeedAllVersionsAndDeletes/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/ContainerManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/CustomDiagnosticAndEventListener.cs
  Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/CustomDiagnosticAndEventListener.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/CustomSerialization.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/DatabaseManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Encryption.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Geospatial/Geospatial.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Handlers/LoggingHandler.cs
  Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/HttpClientFactory.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/IndexManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellRestApi.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/Program.cs
  Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ReEncryption/ReEncryption.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/ReEncryption/ReEncryptionSupport/ReEncryptionIterator.cs
  Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/ServerSideScripts.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/Shared/Shared.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/SystemTextJson.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/TransactionalBatch/TransactionalBatch.csproj
  Microsoft.Azure.Cosmos.Samples/Usage/UserManagement/UserManagement.csproj
Labels: auto-merge

#4713 Routing: Fixes `ExcludeRegions` for `ReadMany` operation.
  Microsoft.Azure.Cosmos/src/ReadManyRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosMultiRegionDiagnosticsTests.cs
Labels: auto-merge

#4712 Documentation: Fixes ReadItemAsync to show return ItemResponse<ToDoActivity> instead of ToDoActivity
  Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Labels: auto-merge

#4679 [INTERNAL] [Client encryption]: Add baseline benchmarks for `Microsoft.Azure.Cosmos.Encryption.Custom`
  Microsoft.Azure.Cosmos.Encryption.Custom/src/AssemblyInfo.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/EncryptionBenchmark.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests.csproj
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/Program.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/Readme.md
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/TestDoc.cs
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/sampledata/testdoc-100kb.json
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/sampledata/testdoc-10kb.json
  Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Performance.Tests/sampledata/testdoc-1kb.json
  Microsoft.Azure.Cosmos.sln
Labels: auto-merge

#4724 Query: Adds deserialization of HybridSearchQueryInfo to the query plan
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/HybridSearchQueryInfo.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/PartitionedQueryExecutionInfo.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/PartitionedQueryExecutionInfoInternal.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionProviderTests.cs
Labels: QUERY, auto-merge

#4673 [Client encryption]: Update MDE dependency to v1.2.0
  Directory.Build.props
  Microsoft.Azure.Cosmos.Encryption.Custom/changelog.md
  Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
Labels: auto-merge

#4632 PatchItemAsync: Adds documentation on behavior of Replace patch operation when replacing properties that do not exist.
  Microsoft.Azure.Cosmos/src/Patch/PatchOperation.cs
Labels: auto-merge

#4711 Azure.Cosmos.Operation => Azure-Cosmos-Operation-Request-Diagnostics
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbEventSource.cs
Labels: auto-merge

#4738 [Internal] Query: Adds an aggregate operator for CountIf. Removes debug assert from QueryPartitionProvider
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateOperator.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionProviderTests.cs
Labels: QUERY, auto-merge
