Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2024-04, with the labels that each got.

#4074 Query: Adds translation support for single key single value select GROUP BY LINQ queries
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Linq/QueryUnderConstruction.cs
  Microsoft.Azure.Cosmos/src/Linq/TranslationContext.cs
  Microsoft.Azure.Cosmos/src/Linq/Utilities.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectTextSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/GroupByClauseSqlParserBaselineTests.Tests.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/SqlObjectVisitorBaselineTests.SqlQueries.xml
Labels: QUERY, auto-merge

#4361 Performance: Refactors query prefetch mechanism
  Microsoft.Azure.Cosmos/src/Pagination/ParallelPrefetch.Testing.cs
  Microsoft.Azure.Cosmos/src/Pagination/ParallelPrefetch.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/ParallelPrefetchTests.cs
Labels: QUERY, auto-merge

#4359 [Internal] Query: Fixes occasional hang while querying using partial partition key against a sub-partitioned container
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/ParallelCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/QueryPartitionRangePageAsyncEnumerator.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/OptimisticDirectExecution/OptimisticDirectExecutionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/PipelineFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/SubpartitionTests.TestQueriesOnSplitContainer.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FactoryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/ParallelCrossPartitionQueryPipelineStageTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionRangePageEnumeratorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/SubpartitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs
Labels: auto-merge

#4353 [Internal] Direct Package: Adds Support for Direct package version 3.33.0
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/Regions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.GroupBy.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.NonValueAggregates.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#4387 [Internal] Query: Fixes Client QL exception by dropping ClientQLCompatibilityLevel
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/OptimisticDirectExecution/OptimisticDirectExecutionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OptimisticDirectExecutionQueryTests.cs
Labels: auto-merge

#4389 [Internal] FaultInjection: Fixes Bug with Headers for TooManyRequests
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionServerErrorResultInternal.cs
Labels: auto-merge

#4379 ContainerProperties: Adds Vector Embedding and Indexing Policy
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/IndexingPolicyDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorEmbeddingPolicyDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorIndexDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/DistanceFunction.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/Embedding.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorDataType.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorEmbeddingPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexPath.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexType.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: auto-merge

#4374 Distributed Tracing: Update operation name for non-generic feed iterator read operation
  Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Labels: auto-merge

#4391 SDK 3.39.0: Adds version bump and changelog.
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.39.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.40.0-preview.0.txt
  changelog.md
Labels: auto-merge

#4401 3.39.0: Adds Cherry Pick Azure Pipeline Yml
  azure-pipelines-official.yml
Labels: auto-merge

#4397 Query: Fixes ResponseMessage not parsing the IndexMetrics as text in latest sdk
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
Labels: QUERY, auto-merge

#4399 [Internal] Benchmarking: Refactors README in Performance tests project
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/README.md
Labels: auto-merge

#4406 [Internal] Distributed Tracing: Fixes Client Config Test
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
Labels: auto-merge

#4416 [Internal] Distributed Tracing: Fixes Client Config Test (#4406)
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
Labels: auto-merge

#4418 [Internal] Distributed Tracing: Fixes Client Config Test (#4406)
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
Labels: auto-merge

#4419 Query: Fixes bug in OrderByCrossPartitionQueryPipelineStage to ensure that errors in inner pipeline creation are bubbled up
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OrderByQueryTests.cs
Labels: QUERY, auto-merge

#4421 [Internal] Security: Fixes Azure.Identity dependency on Microsoft.Azure.Cosmos.Encryption.Custom
  Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
Labels: auto-merge

#4403 [Internal] Query: Adds tests for LINQ GROUP BY Multi-value translations
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Labels: auto-merge

#4426 ChangeFeedProcessor: Fixes a bug properly when dealing with Legacy lease incremental documents that do not have a Mode property
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs
Labels: auto-merge

#4424 [Internal] Flakey Tests: Fixes few Tests in `GatewayAddressCacheTests`
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
Labels: auto-merge

#4430 SDK 3.39.1/3.40.0-preview.1: Adds version bump and changelog.
  Directory.Build.props
  changelog.md
Labels: auto-merge

#4436 SDK 3.40.0-preview.1: Adds version bump and changelog.
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs
  changelog.md
Labels: auto-merge

#4437 SDK 3.39.1: Adds version bump and changelog.
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs
  changelog.md
Labels: auto-merge

#4434 [Internal] ReleaseNotes : Adds known issue to list
  changelog.md
Labels: auto-merge

#4420 Samples: Adds STJ LINQ Serializer Example
  Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs
  Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/Program.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosLinqSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Linq/CosmosLinqJsonConverterTests.cs
Labels: QUERY, auto-merge

#4445 [Internal] Documentation: Adds details about retry backoff for 410/449
  docs/SdkDesign.md
Labels: auto-merge

#4446 Query: Adds a new capability for non streaming order by in QueryFeatures
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryInfo.cs
Labels: QUERY, auto-merge

#4413 Query: Fixes Persisted continuationToken issue by turning off ODE by default
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestDistinctTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestThenByTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OptimisticDirectExecutionQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Labels: auto-merge

#4447 FaultInjection: Adds SendDelay ServerErrorType
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/FaultInjectionServerErrorResultBuilder.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/FaultInjectionServerErrorType.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/ChaosInterceptor.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionRuleStore.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/tests/FaultInjectionDirectModeTests.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/tests/Utils/TestCommon.cs
Labels: auto-merge

#4459 Query: Fixes non streaming order by to use flag from query plan
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/PipelineFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/OrderByPipelineStageBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/OrderByCrossPartitionQueryPipelineStageTests.cs
Labels: QUERY, auto-merge

#4448 FaultInjection: Adds ReadFeed Operation Type
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/FaultInjectionOperationType.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionRuleProcessor.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionServerErrorResultInternal.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/tests/FaultInjectionDirectModeTests.cs
  Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/tests/Utils/TestCommon.cs
Labels: auto-merge

#4460 [Internal] Pipelines: Adds rolling pipeline
  azure-pipelines-rolling.yml
  templates/build-test.yml
Labels: Engineering
