Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2024-11, with the labels that each got.

#4863 VectorIndexDefinition: Refactors Code to Remove Support for `VectorIndexShardKey` from Preview Contract
  Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorIndexDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexPath.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Labels: vector-similarity

#4866 [Internal] JSON Binary Encoding: Adds support for encoding uniform arrays
  Microsoft.Azure.Cosmos/src/Json/IJsonBinaryWriterExtensions.cs
  Microsoft.Azure.Cosmos/src/Json/IJsonWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Enumerator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.NodeTypes.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Numbers.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.TypeMarker.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.UniformArrays.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.ValueLengths.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonTokenType.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriteOptions.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTokenInfo.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
Labels: QUERY, auto-merge

#4868 [Internal] Query: Removes unneeded check on supported query features
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanHandler.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.VectorSearch.xml
Labels: QUERY, auto-merge

#4870 3.45.1: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.45.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.1.txt
  changelog.md
Labels: auto-merge

#4876 [Internal] Query: Adds infrastructure for Hybrid search unit tests
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs
Labels: QUERY, auto-merge

#4649 Query: Fixes prefetching to be disabled when MaxConcurrency is less than or equal to one
  Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/CrossPartitionPartitionRangeEnumeratorTests.cs
Labels: QUERY, auto-merge

#4873 [Hotfix] VectorIndexDefinition: Refactors Code to Remove Support for `VectorIndexShardKey` from Preview Contract
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.45.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.1.txt
  Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorIndexDefinition.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanHandler.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexPath.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/IndexMetricsParserBaselineTest.IndexUtilizationClientSideExistenceTest.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/IndexMetricsParserBaselineTest.IndexUtilizationHeaderLengthTest.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/IndexMetricsParserBaselineTest.IndexUtilizationParse.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.VectorSearch.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  changelog.md
  templates/Cosmos-Emulator.ps1
  templates/emulator-setup.yml
  tools/lessmsi-v2.1.1.zip
Labels: auto-merge

#4839 [Dependencies]: Removes direct reference for Newtonfoft package and add a target build.
  Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
  Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.targets
Labels: auto-merge

#4886 3.45.2: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.45.2.txt
  Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.2.txt
  changelog.md
Labels: auto-merge

#4889 [Hotfix] JSON Binary Encoding: Adds support for encoding uniform arrays
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.45.2.txt
  Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.2.txt
  Microsoft.Azure.Cosmos/src/Json/IJsonBinaryWriterExtensions.cs
  Microsoft.Azure.Cosmos/src/Json/IJsonWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Enumerator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.NodeTypes.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Numbers.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.TypeMarker.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.UniformArrays.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.ValueLengths.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonTokenType.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriteOptions.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTokenInfo.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
  changelog.md
Labels: auto-merge

#4885 Query: Fixes (workaround) for query plan issue where placeholder index does not start at zero
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/FullTextStatistics.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs
Labels: QUERY, auto-merge

#4667 [Internal] Fault Injection: Adds Gateway mode support
  Microsoft.Azure.Cosmos.sln
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionConnectionType.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionRuleBuilder.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionServerErrorType.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionRuleProcessor.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionRuleStore.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorResultInternal.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorRule.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionDirectModeTests.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionGatewayModeTests.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionTests.csproj
  Microsoft.Azure.Cosmos/FaultInjection/tests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
Labels: auto-merge, FaultInjection

#4883 [Internal] JSON Binary Encoding: Adds support for writing unsigned 64-bit integer values
  Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElement.cs
  Microsoft.Azure.Cosmos/src/CosmosElements/Numbers/CosmosNumber64.LazyCosmosNumber64.cs
  Microsoft.Azure.Cosmos/src/CosmosElements/Numbers/CosmosNumber64.cs
  Microsoft.Azure.Cosmos/src/Json/IJsonNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/IJsonWriter.cs
  Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftWriter.cs
  Microsoft.Azure.Cosmos/src/Json/Interop/NewtonsoftToCosmosDBReader.cs
  Microsoft.Azure.Cosmos/src/Json/Interop/NewtonsoftToCosmosDBWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.NodeTypes.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Numbers.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.TypeMarker.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonTextNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNodeType.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonSerializer.cs
  Microsoft.Azure.Cosmos/src/Json/JsonTextParser.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriteOptions.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonTextWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosElementSerializer.cs
  Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
  Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
  Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/CosmosUndefinedQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/DistributedQueryClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Json/JsonMicroBenchmarksBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Json/Utils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosElements/LazyCosmosElementTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/DeserializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNewtonsoftNavigator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTokenInfo.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
Labels: QUERY, auto-merge

#4897 [Internal| FaultInjection: Adds docs
  Microsoft.Azure.Cosmos/FaultInjection/README.md
  Microsoft.Azure.Cosmos/FaultInjection/changelog.md
Labels: auto-merge, FaultInjection

#4893 3.46.0: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.46.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.47.0-preview.txt
  changelog.md
Labels: auto-merge

#4896 [Client encryption]: Fixes missing files errors at time of nuget publishing.
  Icon.png
  Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
  Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Labels: auto-merge

#4902 Revert "[INTERNAL] CI: Fixes Revert disabling Binskim as nuget repo failing (#4785)"
  templates/static-tools.yml
Labels: auto-merge

#4682 OpenTelemetry Metrics: Adds support to collect Operation level metrics
  Microsoft.Azure.Cosmos/src/CosmosClient.cs
  Microsoft.Azure.Cosmos/src/CosmosClientTelemetryOptions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/AppInsightClassicAttributeKeys.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbClientMetrics.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbMeterUtil.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbOperationMeter.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/DatabaseDupAttributeKeys.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/IActivityAttributePopulator.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/TracesStabilityFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Metrics/CustomMetricExporter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Metrics/OpenTelemetryMetricsTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemBenchmarkHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Bulk/MockedItemBulkBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/OTelExporter/CustomMetricExporter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/OTelExporter/CustomTraceExporter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Program.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: Telemetry, auto-merge

#4857 Query: Adds LINQ support for Multi-key Group By translation
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Linq/QueryUnderConstruction.cs
  Microsoft.Azure.Cosmos/src/Linq/TranslationContext.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiKeyTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
Labels: auto-merge

#4867 FaultInjection: Adds method to add FaultInjection using CosmosClientBuilder
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjector.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/FaultInjection/IFaultInjector.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/ContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge, FaultInjection

#4901 [Internal] Binary Encoding: Fixes Performance Regression
  Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Labels: auto-merge

#4908 [Internal] Pipelines: Fixes setting connection string environment variable
  templates/build-test.yml
Labels: auto-merge

#4905 [Internal] FaultInjection: Refactors FaultInjection Tests
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionRuleProcessor.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionDirectModeTests.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionGatewayModeTests.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/Utils/TestCommon.cs
Labels: auto-merge, FaultInjection

#4706 Hedging: Adds support for writes on multi region accounts
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs
  Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/IGlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Labels: auto-merge, Hedging

#4909 [Internal] Pipelines: Adds FI pipeline YMLs
  Directory.Build.props
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj
  azure-pipelines-faultinjection.yml
  templates/build-fault-injection-test.yml
  templates/fault-injection-nuget-pack.yml
Labels: auto-merge, FaultInjection

#4913 [Internal] Pipelines: Fixes FaultInjection Release Pipelines
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionDirectModeTests.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionGatewayModeTests.cs
  azure-pipelines-faultinjection.yml
  templates/build-fault-injection-test.yml
  templates/fault-injection-nuget-pack.yml
Labels: auto-merge

#4914 [Internal] FaultInjection: Fixes csproj so it will generate with a strong signed package name
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj
Labels: auto-merge, FaultInjection

#4714 [Internal] Query: Adds Query Advisor SDK capabilities
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
  Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
  Microsoft.Azure.Cosmos/src/Headers/CosmosMessageHeadersInternal.cs
  Microsoft.Azure.Cosmos/src/Headers/CosmosQueryResponseMessageHeaders.cs
  Microsoft.Azure.Cosmos/src/Headers/Headers.cs
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/QueryAdvice.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/QueryAdviceEntry.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/QueryAdviceRuleDocumentation.xml
  Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/RuleDirectory.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/FeedResponse.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/QueryAdvisorBaselineTest.QueryAdviceParse.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryAdvisorBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryAdvisorTest.cs
Labels: auto-merge
