Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-02, with the labels that each got.

#4990 [Internal] Direct Package: Adds support for direct package version 3.37.9
  Directory.Build.props
Labels: auto-merge

#4997 Hedging: Adds GA for DisableAvailabilityStrategy
  Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge, Hedging

#4995 Open Telemetry: Fixes attribute name as per OTel Guidance
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbClientMetrics.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Metrics/OpenTelemetryMetricsTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/CustomListener.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/TracesStabilityFactoryTests.cs
Labels: auto-merge

#4943 [Internal] Binary Encoding: Adds performance tests with binary encoding enabled.
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemBenchmarkHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemOfTBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemStreamBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockRequestHelper.cs
  templates/build-test.yml
Labels: auto-merge

#4994 Query: Adds Computed Properties to Public Interface
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ComputedPropertiesDefinition.cs
  Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ComputedProperty.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: auto-merge

#5000 [Internal 3.47.0: Refactors some APIs to be PREVIEWonly
  Microsoft.Azure.Cosmos/src/CosmosClientTelemetryOptions.cs
  Microsoft.Azure.Cosmos/src/NetworkMetricsOptions.cs
  Microsoft.Azure.Cosmos/src/OperationMetricsOptions.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbClientMetrics.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#4984 3.47.0: Adds Version Bump and Changelog
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.47.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.0.txt
  changelog.md
Labels: auto-merge

#5002 [Internal] Pipelines: Fixes pipeline release run
  azure-pipelines-official.yml
Labels: auto-merge

#5005 [Internal] Open Telemetry : Fixes preview pipeline test for open telemetry
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Metrics/OpenTelemetryMetricsTest.cs
Labels: auto-merge

#5009 [Internal] Binary Encoding: Refactors performance tests timeout period.
  templates/build-test.yml
Labels: auto-merge

#5012 [Internal] Pipelines: Adds all tests that are ran during release pipelines to PR runs
  azure-pipelines.yml
Labels: auto-merge, flaky tests

#4989 [FaultInjection] Metadata Requests: Adds Metadata request support for FaultInjection
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionCondition.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionOperationType.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionRuleBuilder.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionServerErrorType.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionConditionInternal.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionRuleProcessor.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorResultInternal.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionMetadataTests.cs
  Microsoft.Azure.Cosmos/FaultInjection/tests/Utils/TestCommon.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClient.cs
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAccountReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
Labels: auto-merge, FaultInjection

#5013 Direct Package: Adds upgrade to 3.37.10
  Directory.Build.props
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
Labels: auto-merge

#5020 Direct code: Adds a direct package that contains a fix for Faster detection of broken transport connections.
  Directory.Build.props
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
Labels: auto-merge

#5022 3.47.1: Adds build props for sdk-hotfix-release-3.47.1
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.47.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.1.txt
  changelog.md
Labels: auto-merge

#5011 Query: Adds query feature and deserialization of component weights for weighted rank fusion
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/HybridSearchQueryInfo.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionProviderTests.cs
Labels: QUERY, auto-merge

#4980 Query: Adds FullTextContains, FullTextContainsAll, FullTextContainsAny as LINQ extension method
  Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
  Microsoft.Azure.Cosmos/src/ClientResources.resx
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/BuiltinFunctionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/SqlBuiltinFunctionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlFunctionCallScalarExpression.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestFullTextContainsFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#5026 3.47.1 hotfix: Adds build props for sdk-hotfix-release-3.47.1
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.47.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.1.txt
  changelog.md
Labels: auto-merge

#5030 [Internal] Binary Encoding: Fixes Serialization Gaps on Newtonsoft Reader/Writer for Transactional Batch
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs
  Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftReader.cs
  Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/NewtonsoftInteropTests.cs
Labels: auto-merge, BinaryEncoding

#5040 3.47.2: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.47.2.txt
  Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.2.txt
  changelog.md
Labels: auto-merge

#5041 [Hotfix] Binary Encoding: Fixes Serialization Gaps on Newtonsoft Reader/Writer for Transactional Batch
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.47.2.txt
  Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.2.txt
  Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs
  Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftReader.cs
  Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/NewtonsoftInteropTests.cs
  changelog.md
Labels: auto-merge
