Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-06, with the labels that each got.

#5180 Query: Adds public PopulateQueryAdvice capability
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/FeedResponse.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/ReadFeedResponse.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#5227 [Internal] Binary Encoding: Fixes encoding for multi-byte user defined strings
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
  Microsoft.Azure.Cosmos/src/Json/JsonStringDictionary.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
Labels: auto-merge, BinaryEncoding

#5221 Query : Fixes Skip + Order By Bug
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/PipelineFactory.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestOrderByTranslation.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/CosmosUndefinedQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/MockCosmosQueryClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/NegativeQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/PopulateIndexMetricsTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryAdvisorTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
Labels: LINQ, auto-merge

#5214 [Internal] Thin Client Integration: Adds runner tests for bulk and batch operations.
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemThinClientTests.cs
Labels: auto-merge, thin-client-integration

#5234 Client Encryption: Fixes Encryption Release Pipeline
  azure-pipelines-encryption-custom-official.yml
  azure-pipelines-encryption-custom.yml
  azure-pipelines-encryption-official.yml
  azure-pipelines-encryption.yml
  templates/encryption-custom-nuget-pack.yml
  templates/encryption-nuget-pack.yml
  templates/static-tools-encryption-custom.yml
  templates/static-tools-encryption.yml
Labels: bug, auto-merge

#5241 Direct Package Upgrade: Fixes `Cosmos.Direct` Package to `3.39.1`
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/Regions.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs
  Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
  Microsoft.Azure.Cosmos/src/Util/SubStatusMappingUtil.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestVectorDistanceFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.Distinct.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.OffsetLimit.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.Top.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs
Labels: auto-merge

#5248 3.52.0: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.52.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.53.0-preview.0.txt
  changelog.md
Labels: auto-merge

#5076 [Internal] Gates: Fixes bug where CosmosOperaitonCancellationException is now thrown in CancellationTokenTests
  Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
Labels: auto-merge

#5261 [Internal] PPAF: Fixes Integration Tests to Intercept Gateway Response
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/MockSetupsHelper.cs
Labels: auto-merge, PerPartitionAutomaticFailover

#5252 TokenCredentialCache: Adds an options to override AAD audience scope.
  Microsoft.Azure.Cosmos/src/Authorization/TokenCredentialCache.cs
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAadTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/LocalEmulatorTokenCredential.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosAuthorizationTests.cs
Labels: auto-merge

#5246 [Internal] Binary Encoding: Fixes JsonStringDictionary to allow duplicates
  Microsoft.Azure.Cosmos/src/Json/JsonStringDictionary.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonStringDictionaryTests.cs
Labels: QUERY, auto-merge, BinaryEncoding
