Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-08, with the labels that each got.

#5323 [Internal] Thin Client Integration: Removes ThinClientStoreModel and uses GatewayStoreModel for better code modularity.
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
  Microsoft.Azure.Cosmos/src/ThinClientStoreClient.cs
  Microsoft.Azure.Cosmos/src/ThinClientStoreModel.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemThinClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CancellationTokenTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ExceptionlessTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ThinClientStoreClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ThinClientStoreModelTests.cs
Labels: auto-merge, thin-client-integration

#5313 Query: Adds GetIndexMetrics LINQ extension method
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/CosmosItemLinqTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#5269 [Internal] [FaultInjection] ThinClient: Fixes payload of injected errors for requests going to ThinClient Proxy
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionRuleProcessor.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorResultInternal.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
  Microsoft.Azure.Cosmos/src/ThinClientStoreClient.cs
Labels: thin-client-integration, FaultInjection

#5346 3.53.0: Adds new SDK version and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.53.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.54.0-preview.0.txt
  changelog.md
Labels: auto-merge

#5368 VectorDataType: Adds Support for `Float16` Data Type
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorDataType.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Labels: auto-merge, vector-similarity

#5345 [Internal] Thin Client Integration: Fixes 400/1041 Error for Query Operations in Thin Client Mode.
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemThinClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/RegionFailoverTests.cs
  azure-pipelines-msdata-direct.yml
  azure-pipelines.yml
  templates/build-thinclient.yml
Labels: auto-merge

#5371 [Internal] Query : Adds new test project for AOT
  Microsoft.Azure.Cosmos.sln
  Microsoft.Azure.Cosmos/src/AssemblyInfo.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Common/ConfigurationManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Common/RestHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Common/TestUtil.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/MSTestSettings.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Microsoft.Azure.Cosmos.Tests.Aot.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Query/QueryTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/RestHelperTest.cs
Labels: auto-merge

#5364 TokenCredentialCache: Adds a fallback mechanism to AAD scope override.
  Microsoft.Azure.Cosmos/src/Authorization/CosmosScopeProvider.cs
  Microsoft.Azure.Cosmos/src/Authorization/IScopeProvider.cs
  Microsoft.Azure.Cosmos/src/Authorization/TokenCredentialCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAadTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/LocalEmulatorTokenCredential.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Authorization/CosmosScopeProviderTests.cs
Labels: auto-merge

#5378 3.53.1: Adds hotfix release 3.53.1
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.53.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.54.0-preview.1.txt
  changelog.md
Labels: auto-merge
