Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-09, with the labels that each got.

#5416 [Internal] Pipeline: Fixes pipelines by fixing the StoredProc and UserDefined Script Blacklisting emulator tests
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
Labels: auto-merge

#5411 Hedging: Adds GA for adding hedging via RequestOptions
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge, Hedging

#5401 [Internal]Nregion: Adds support for including nregioncommit synchronous for less than Strong Consistency
  Directory.Build.props
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
  Microsoft.Azure.Cosmos/src/ThinClientTransportSerializer.cs
  Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DocumentClientUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSerializerUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosSerializerCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StoreReaderTest.cs
Labels: auto-merge, PerPartitionAutomaticFailover, n-region-synchronous-commit
