Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-10, with the labels that each got.

#5427 PPAF: Fixes issue where setting `RequestTimeout` to `0` second will cause PPAF dynamic enablement to break
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
Labels: auto-merge, PerPartitionAutomaticFailover

#5432 VectorDataType: Fixes Enum Ordering for `Float16` Data Type
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorDataType.cs
Labels: auto-merge, vector-similarity

#5437 MSRC: Fixes dummy account endpoint and keys in tests
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ActiveClientDiagnosticTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs
Labels: auto-merge
