Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-04, with the labels that each got.

#5099 [Internal] Code Analysis Rules: Fixes analyzer issues in Exception classes.
  .globalconfig
  Microsoft.Azure.Cosmos/src/Batch/BatchAsyncBatcher.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs
  Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Observers/ChangeFeedObserverContextCore.cs
  Microsoft.Azure.Cosmos/src/ExceptionHandlingUtility.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/src/Handler/DiagnosticsHandlerHelper.cs
  Microsoft.Azure.Cosmos/src/Handler/TelemetryHandler.cs
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
  Microsoft.Azure.Cosmos/src/Query/Core/ExceptionToCosmosException.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Monads/ExceptionWithStackTraceException.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Monads/TryCatch{TResult}.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/src/ReadFeed/ReadFeedIteratorCore.cs
  Microsoft.Azure.Cosmos/src/RenameCollectionAwareClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosExceptionFactory.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosNullReferenceException.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosObjectDisposedException.cs
  Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosOperationCanceledException.cs
  Microsoft.Azure.Cosmos/src/ResourceThrottleRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/AsyncCacheNonBlocking.cs
  Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
  Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheelCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs
Labels: auto-merge

#5105 [Internal] Binary Encoding: Fixes User String Dictionary Interface Name
  Microsoft.Azure.Cosmos/src/Json/IJsonBinaryWriterExtensions.cs
  Microsoft.Azure.Cosmos/src/Json/IJsonStringDictionary.cs
  Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonNavigator.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonReader.cs
  Microsoft.Azure.Cosmos/src/Json/JsonStringDictionary.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
  Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Json/JsonRoundTripBenchmarks.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Json/PocoDeserializerBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonStringDictionaryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
Labels: QUERY, auto-merge

#5106 Diagnostics: Fixes bug where some overloaded substatus codes are displayed incorrectly in diagnostics.
  Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Labels: auto-merge

#5088 [Internal]Thin Client Integration: Adds ThinProxy endpoint in account properties after retrieval from Gateway.
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
  Microsoft.Azure.Cosmos/src/ThinClientConstants.cs
  Microsoft.Azure.Cosmos/src/ThinClientStoreModel.cs
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GlobalEndpointManagerTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ThinClientStoreModelTests.cs
Labels: auto-merge

#5101 [Internal] Direct package: Adds direct package version 3.38.0 to SDK
  Directory.Build.props
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/ChaosInterceptor.cs
  Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.OffsetLimit.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.Top.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/QueryPartitionProviderTestInstance.cs
Labels: auto-merge

#5115 [Internal] Thin Client Integration: Fixes config refresh and gateway mode check.
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Labels: auto-merge, thin-client-integration

#5120 Query: Adds an environment variable for disabling the hybrid search query plan optimization
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanHandler.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
  Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/NonStreamingOrderByQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/ParsingBenchmark.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionProviderTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/SubpartitionTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/PartitionRoutingHelperTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs
Labels: QUERY, auto-merge

#5108 Metadata requests: Fixes bug where certain metadata requests are not retried with a client cold start with only query requests
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionRuleBuilder.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionServerErrorType.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorResultInternal.cs
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyRangeCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MetadataRequestThrottleRetryPolicyTests.cs
Labels: auto-merge

#5124 [Internal] 3.48.1: Refactors changelog + version for 3.48.1 hotfix
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.48.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.49.0.preview.1.txt
  changelog.md
Labels: auto-merge

#5125 [Internal] Release: Adds Cherry-Pick Metadata PR Fix to release branch
  Directory.Build.props
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionRuleBuilder.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionServerErrorType.cs
  Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorResultInternal.cs
  Microsoft.Azure.Cosmos/contracts/API_3.48.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.49.0.preview.1.txt
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyRangeCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MetadataRequestThrottleRetryPolicyTests.cs
  changelog.md
Labels: auto-merge

#5123 [Internal] Binary Encoding: Adds Client Option to Enable/Disable Request and Response Stream Conversation
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: auto-merge, BinaryEncoding

#5134 [Internal] Query: Adds InternalsVisbility to all query oracle project
  Microsoft.Azure.Cosmos/src/AssemblyInfo.cs
Labels: auto-merge

#5127 UnknownRntbdHeader : Adds a new SDK capability for UnknownRntbdHeaders
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/ContractTests.cs
Labels: auto-merge

#5128 Session Consistency: Adds SessionTokenMismatchRetryPolicy optimization through customer supplied region switch hints
  Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/SessionRetryOptions.cs
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SessionRetryOptionsTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SessionRetryOptionsUnitTests.cs
Labels: auto-merge

#5126 [INTERNAL] AddressEnumerator: Fixes IndexOutOfRangeException Observed in AddressEnumerator
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Labels: auto-merge

#5133 [Internal] Binary Encoding: Fixes `DateTime` Parsing Issue
  Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/NewtonsoftInteropTests.cs
Labels: auto-merge, BinaryEncoding

#5136 VectorIndexing: Adds Preview APIs for VectorIndexing Policies
  Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorIndexDefinition.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexPath.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
Labels: auto-merge, vector-similarity

#5139 Query: Fixes flip of boolean switch for hybridSearchSkipOrderByRewrite
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/PartitionedQueryExecutionInfoInternal.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs
Labels: QUERY, auto-merge

#5140 [Internal] 3.49.0: Adds Version bump, changelog, and contracts
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.49.0-preview.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.49.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.50.0-preview.0.txt
  changelog.md
Labels: auto-merge

#5137 [Internal] Thin Client Integration: Fixes the ThinClientTransportSerializer to avoid creating memory stream.
  Microsoft.Azure.Cosmos/src/ThinClientTransportSerializer.cs
Labels: auto-merge

#5141 [Internal] Thin Client Integration: Adds HTTP Client Sharing between Gateway and Thin Client
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/ThinClientTransportSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Labels: auto-merge, thin-client-integration

#4993 Query: Adds LINQ extension method for ORDER BY RANK, FullTextScore and RRF
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/BuiltinFunctionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/OtherBuiltinSystemFunctions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/Linq/QueryUnderConstruction.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlFunctionCallScalarExpression.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestFullTextScoreOrderByRankFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestOrderByRankFunctionComposeWithOtherFunctions.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestRRFOrderByRankFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge
