Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-05, with the labels that each got.

#5152 [Internal] Thin Client Integration: Fixes location cache update for thinclient read and write locations.
  Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Labels: auto-merge, thin-client-integration

#5163 Query: Fixes function signature for RRF, OrderByRank and FullTextScore LINQ extension methods
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/OtherBuiltinSystemFunctions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestFullTextScoreOrderByRankFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestRRFOrderByRankFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#5121 Query: Adds support for the optimized query plan that skips the order by rewrite
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchQueryResult.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs
Labels: QUERY, auto-merge

#5171 Query: Fixes default for the query plan optimization for Hybrid Search to be disabled
  Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/NonStreamingOrderByQueryTests.cs
Labels: QUERY, auto-merge

#5176 Version bump: Adds changelog, and contracts for version 3.49.1 release
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.49.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.50.0-preview.1.txt
  changelog.md
Labels: auto-merge

#5183 Version bump: Adds changelog, and contracts for version 3.49.1 release (Cherry-Pick)
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.49.1.txt
  Microsoft.Azure.Cosmos/contracts/API_3.50.0-preview.1.txt
  changelog.md
Labels: QUERY, auto-merge

#5172 Query: Fixes FullText Policy API by making language optional
  Microsoft.Azure.Cosmos/src/Resource/Settings/FullTextPath.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
Labels: auto-merge

#5165 [Internal] PPAF: Adds Code to Enable Read Hedging By Default
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerTests.cs
Labels: auto-merge, PerPartitionAutomaticFailover

#5189 Hedging: Fixes Concurrency Issue
  Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
Labels: auto-merge, Hedging

#5190 Hedging: Adds Hedging for Write requests GA
  Microsoft.Azure.Cosmos.Samples/Usage/Hedging/ReadRequestDiagnosticsExample.json
  Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
  docs/Cross Region Request Hedging.md
Labels: auto-merge, Hedging

#5192 3.50.0: Adds version bump and changelog
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.50.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.51.0-preview.0.txt
  changelog.md
Labels: auto-merge

#5181 [Internal] Query: Fixes QueryAdviceRuleDocumentation
  Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/QueryAdviceRuleDocumentation.xml
  Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/RuleDirectory.cs
Labels: auto-merge

#5194 [Internal] Changelog: Fixes Changelog
  changelog.md
Labels: auto-merge

#5204 3.51.0: Adds new SDK versions and contract files
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.51.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.52.0-preview.0.txt
  changelog.md
Labels: auto-merge

#5157 Query: Adds support for LINQ extension method for VectorDistance
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/BuiltinFunctionVisitor.cs
  Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/OtherBuiltinSystemFunctions.cs
  Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
  Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlFunctionCallScalarExpression.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestRRFOrderByRankFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestVectorDistanceFunction.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTranslationBaselineTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#5149 [Internal] Query: Fixes Perf Tests
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/ContentSerializationPerformanceTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/QueryStatisticsDatumVisitor.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/settings.json
Labels: QUERY, auto-merge

#5195 [Internal] Thin Client Integration: Adds runner tests for thinclient test scenarios.
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemThinClientTests.cs
  azure-pipelines.yml
  templates/build-test.yml
  templates/build-thinclient.yml
Labels: auto-merge

#5186 [Internal] Thin Client Integration: Adds proxy request headers startEPK and endEPK for query operation.
  Microsoft.Azure.Cosmos/src/ThinClientStoreClient.cs
  Microsoft.Azure.Cosmos/src/ThinClientTransportSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ThinClientStoreClientTests.cs
Labels: auto-merge, thin-client-integration

#5218 [Internal] Binary Encoding: Fixes DateTime Parsing Issue with Trailing Zeros in the Milli-Seconds Precision.
  Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftWriter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/NewtonsoftInteropTests.cs
Labels: auto-merge, BinaryEncoding
