Repository Azure/azure-cosmos-dotnet-v3, pull requests merged in 2025-03, with the labels that each got.

#5028 [Internal] PPAF: Adds PPAF information to diagnostics
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/UserAgentFeatureFlags.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Labels: auto-merge, PerPartitionAutomaticFailover

#5037 [Internal] Query: Adds InternalsVisibility to Query Oracle
  Microsoft.Azure.Cosmos/src/AssemblyInfo.cs
Labels: auto-merge

#5057 AvailabilityStrategy: Adds WithAvailabilityStrategy method to public GA
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge, Hedging

#5058 [Internal] Binary Encoding: Fixes serializer for non-point operations.
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadManyItemsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Labels: auto-merge

#5017 AddressRefresh: Fixes behavior of AddressRefresh calls so they preform cross regional retries
  Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
Labels: auto-merge

#4978 Scripts: Adds Stream APIs for CRUD Operations
  Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
  Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsInlineCore.cs
  Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Labels: auto-merge

#4977 Heiarchical Partition Keys: Fixes bug for ReadMany where `None` Partition does not return results
  Microsoft.Azure.Cosmos/src/ReadManyQueryHelper.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosMultiHashTest.cs
Labels: auto-merge

#5023 [Internal] Circuit Breaker: Adds Code to Implement Per Partition Circuit Breaker
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Diagnostics/UserAgentFeatureFlags.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/RetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerNoOp.cs
  Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerUnitTests.cs
Labels: auto-merge, PerPartitionAutomaticFailover

#5064 Query: Adds support for weighted RRF in hybrid search
  Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchCrossPartitionQueryPipelineStage.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
  Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs
Labels: QUERY, auto-merge

#5065 3.48.0: Adds changlog updates and version bump
  Directory.Build.props
  Microsoft.Azure.Cosmos/contracts/API_3.48.0.txt
  Microsoft.Azure.Cosmos/contracts/API_3.49.0-preview.0.txt
  changelog.md
Labels: auto-merge

#5073 [INTERNAL] AsyncCache: Adds Parameter to Enable Exception Handling Using `CosmosClientOptions`
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
  Microsoft.Azure.Cosmos/src/Routing/AsyncCache.cs
  Microsoft.Azure.Cosmos/src/Routing/AsyncCacheNonBlocking.cs
  Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
  Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs
  Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
  Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CancellationTokenTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSynchronizerCoreTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeCacheTest.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/AsyncCacheNonBlockingTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs
Labels: auto-merge

#5081 [Interna]] Changelog: Fixes Changelog
  changelog.md
Labels: auto-merge

#5077 ThroughputBucketing: Adds changes to make ThroughputBucket public for preview SDK
  Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
  Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
  Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Labels: auto-merge

#5019 [Internal]Thin Client Integration: Adds Classes and Methods for Transport Serialization of RNTBD Payload
  Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
  Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
  Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
  Microsoft.Azure.Cosmos/src/ThinClientConstants.cs
  Microsoft.Azure.Cosmos/src/ThinClientStoreClient.cs
  Microsoft.Azure.Cosmos/src/ThinClientStoreModel.cs
  Microsoft.Azure.Cosmos/src/ThinClientTransportSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ThinClientStoreClientTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ThinClientStoreModelTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ThinClientTransportSerializerTests.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockCosmosUtil.cs
Labels: auto-merge

#5063 [Internal] ClientRetryPolicy: Adds Code to Apply Partition Level Override When a Requested Cancellation Token Expires
  Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
  Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
  Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
Labels: auto-merge, PerPartitionAutomaticFailover

#5052 [Internal] Query: Adds Support for ORDER BY RANK in SQL DOM
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/CstToAstVisitor.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/IsqlListener.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/IsqlVisitor.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/sql.g4
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/sqlBaseListener.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/sqlBaseVisitor.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/sqlLexer.cs
  Microsoft.Azure.Cosmos/src/Query/Core/Parser/sqlParser.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlOrderByItem.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/SqlOrderbyClause.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectEqualityVisitor.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectHasher.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectObfuscator.cs
  Microsoft.Azure.Cosmos/src/SqlObjects/Visitors/SqlObjectTextSerializer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/OrderByClauseSqlParserBaselineTests.MultiOrderByRank.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/OrderByClauseSqlParserBaselineTests.SingleOrderByRank.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/SqlObjectVisitorBaselineTests.SqlQueries.xml
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OfflineEngine/SqlInterpreter.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Parser/OrderByClauseSqlParserBaselineTests.cs
Labels: auto-merge

#5091 [Internal] Code Analysis Rules: Fixes analyzer issues in Cosmos project.
  Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
  Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
  Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj
  Microsoft.Azure.Cosmos/src/Authorization/TokenCredentialCache.cs
  Microsoft.Azure.Cosmos/src/DocumentClient.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
  Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
  Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollector.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/AppInsightClassicAttributeKeys.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbMeterUtil.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbOperationMeter.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryAttributeKeys.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse.cs
  Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryResponse{T}.cs
  Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
  Microsoft.Azure.Cosmos/src/ThinClientStoreModel.cs
  Microsoft.Azure.Cosmos/src/Util/Extensions.cs
  Microsoft.Azure.Cosmos/src/WebExceptionRetryPolicy.cs
  Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Labels: auto-merge
